### ISSUE TITLE
Airspace dialogs on OpenGL

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#1046]
http://www.postfrontal.com/forum/topic.asp?TOPIC_ID=8498

**Comment by brunotl** [comment]
I can't replicate, more info requiered ...

**Comment by pventafridda** [comment]
Argh.. for me it is well replicated at first try.
load demo airspace
display airspaces on screen . maybe optional
long click on map near to airspace, outside of it
on demo I get selection of near places: CTR C BERgAMO and Valbrembo airport
i click on CTR airspace, it becomes yellow
Then I click on SELECT.

What happens: there screen keep changing between main map and the dialog  page in a 3 seconds cycle.
Second A: Map, Second B: dialog with yellow highlighted CTR C BERGAMO, Second Cialog without highlighted CTR C:
Back to map.
When on dialog page, buttons not working.
To exit the loop, change multimap when on the map page.

**Comment by parapenT1sta** [comment]
I tried and I couldn't replicated it. I am running Android 7.1.1 on Nexus 6P.

**Comment by pventafridda** [comment]
I am running 6.0.1 on S5 NEO.
If you cant replicate  I will later tonight check on configuration.

**Comment by parapenT1sta** [comment]
I did profile reset to make sure and I still can't replicated it in Fly and
Sim mode but I will keep trying it.

**Comment by pventafridda** [comment]
it happens on android 6 Huawey P9 Lite

**Comment by pventafridda** [comment]
It is a bad general bug involving SetTimerNotify in all dialogs. Existing also in other dialogs. I have fixed .

**Comment by brunotl** [comment]
are you sure it's related to timer ?

**Comment by pventafridda** [comment]
if you compile  a beta I can tell you quickly


In data 27 Febbraio 2017 7:54:40 PM Bruno de Lacheisserie 
<notifications@github.com> ha scritto:

**Comment by pventafridda** [comment]
Now we know it is not related to timer. It is related to the airspace dialogs that are popped up.

**Comment by pventafridda** [comment]
Some more details.
The problem happens (also) inside dlgMultiSelectList.cpp  after calling dlgMultiSelectListDetailsDialog.
Same problem if called from OnMultiSelectLisListEnter or OnEnterClicked.
The 3 seconds cycle (map-dialog-dialog with highleghted Select button) is quite strange.
In fact after showing again the old dialog, the following second is showing the SELECT button highlighted like if someone had clicked on it.

I could notice a similar behaviour in Sysop Mode after resizing the screen. Old dialog for text entry still active in the rest of the page, and it is ok. But it actually keeps looping in a 3 seconds cycle, showing the dialog without keypresses, and then with the semi-last key pressed and then the very last key pressed.
Example: from Pilot name I enter RES0800x0400 and then OK. 
The dialog will show text keyboard with no highlighted keys, then with 0 highlighted, then with OK button highlighted.

**Comment by brunotl** [comment]
put break point in dlgAirspaceDetails() and look call stack ...

**Comment by pventafridda** [comment]
Latest master does not have the problem anymore. If the problem is inside libraries, we need to create another issue. This particular problem is now solved.

**Comment by pventafridda** [comment]
Also in 6.1e problem is gone. Closing.
