### ISSUE TITLE
Android 2.3.7 Auto-Brightness crash LK8000?

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#1051]
http://www.postfrontal.com/forum/topic.asp?TOPIC_ID=8483&whichpage=4

Dell Streak 5 running CM7.

**Comment by pventafridda** [comment]
For me this unsupported hardware.

**Comment by pventafridda** [comment]
I am closing this, there are no evidences that auto brightness can cause the problem on ancient hardware more than changing sound volume or switching on the torch,
