### ISSUE TITLE
 track value seems never over 180 when logger replay @android version

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#1055]
I got this report from PGForum:

_There is a question that track value seems never over 180 when logger replay @ android version. 
I'm not sure whether it is correct in fly mode. 
Track value is correct with lk8000 6.0b @ PC & WinCE which I confirmed.

http://www.paraglidingforum.com/viewtopic.php?p=p522128#p522128

![lk8000 track issue](https://cloud.githubusercontent.com/assets/608650/23528995/08e3b052-ff9c-11e6-8f1e-c47f358d128b.jpg)

**Comment by pventafridda** [comment]
Only on Android? Hardly possible.
Can you please check yourself ? If you can replicate I will check the code.

**Comment by brunotl** [comment]
in screenshot, value is abs value of Track bearing in  [-180 : 180] range.

2 bug behind that
first is already fixed by commit a22bdf0892ea88dc8e531b6073e32734ddb90e4c
second is old bug line 569 of LKProcess.cpp, but is hidden by first fix in 6.1d

same as issue #1017
