### ISSUE TITLE
Rotate screen not working properly (tested on Linux only)

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#1059]
- Open LK8000 (in Linux)
- Config 1/2 - Screen Modes - 840x480
- Turn Screen

(compiled LK8000 with the latest commits up to this date)

**Comment by pventafridda** [comment]
Duplicated https://github.com/LK8000/LK8000/issues/859

From: Sérgio Da Silva 
Sent: Monday, March 06, 2017 11:18 PM
To: LK8000/LK8000 
Cc: Subscribed 
Subject: [LK8000/LK8000] Rotate screen not working properly (tested on Linux only) (#1059)

  a.. Open LK8000 (in Linux) 
  b.. Config 1/2 - Screen Modes - 840x480 
  c.. Turn Screen 
(compiled LK8000 with the latest commits up to this date)

**Comment by parapenT1sta** [comment]
Sorry.
