### ISSUE TITLE
CAirspaceManager FillAirspacesFromOpenAir CorrectGeoPoints

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#1071]
Inside this function, we call CorrectGeoPoints(points)  and "points" is not used (ex. by a pushback) and not even initialized!

**Comment by brunotl** [comment]
points is initialized by ctor line 1531 and if no push_back, container is empty,  checked by first line of CorrectGeoPoints().

**Comment by pventafridda** [comment]
Right, it is a class, not a simple struct, and it has a constructor.
