### ISSUE TITLE
Assertion failure on Kobo

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#1088]
6.1F
KoboMini+BFV ver 10. Error (Update from version 60b)

After startup and on the waiting GPS fix I am get one error and only I can restart device.

CRITICAL ASSERTION FAILURE !
Execution failure in file
Common/Source/device.cpp
at line 65

LK8000 terminated !

**Comment by pventafridda** [comment]
Is this now closed after your latest fixes, Bruno?

**Comment by brunotl** [comment]
no, i have only added more diagnostic, for know where we use LockComm inside RxThread.

**Comment by pventafridda** [comment]
So we need to check this out before releasing 6.1g for kobo
