### ISSUE TITLE
Download airspace / maps / waypoints from the web to simplify setup

### ISSUE THREAD

**Issue by rcoh** [LK8000/LK8000#1098]
Discussed in #1097, this would significantly simplify configuration for new users

**Comment by ToninoTarsi** [comment]
I think Maps problem is already solved.
For Waypoint I can easily add it to LKMAPS provided someone makes a list of links to use. Unfortunately I can not help for that list. In HG waypoints are not so stable and vary  very often. If I got that list for Gliding  I will add then immediately,

**Comment by AlphaLima** [comment]
I think GIT is already the best platform for that,
here I made some initial data,
would that be OK for you?

Am 11.05.2017 um 14:37 schrieb Tonino Tarsi:

**Comment by AlphaLima** [comment]
https://github.com/AlphaLima/LK8000_Data

Am 11.05.2017 um 14:37 schrieb Tonino Tarsi:

**Comment by ToninoTarsi** [comment]
Yes ... something like this can work ..

**Comment by AlphaLima** [comment]
Thanks to Toni:
https://play.google.com/store/apps/details?id=org.lk8000.lkmap
