### ISSUE TITLE
WiFi on Kobo Glo HD

### ISSUE THREAD

**Issue by ToninoTarsi** [LK8000/LK8000#1106]
After last Kobo Glo HD firmware update LK8000 is not more able to connect to any WiFi hotspots.
As suggested by Bruno issue is similar to : https://github.com/koreader/koreader/issues/2554
I have a friend affected by this and just making some tests adding -Dwext to wpa_supplicant.

**Comment by brunotl** [comment]
it's seem's problem is linked to kobo firmware update from version 4.2.8432 (1/9 Feb 2017), so all model can be concerned excepted Mini.

**Comment by ToninoTarsi** [comment]
Adding "-D wext" to wpa_supplicant solve the problem on the GloHD with new Firmware and also work on  GloHD with old firmware.
I also tested  Kobo GLO device and works fine.
Left to test are Aura,mini  and Touch devices.

**Comment by brunotl** [comment]
Tested on Mini and Touch 2 and Aura 2  that work.

**Comment by ToninoTarsi** [comment]
Great!!!

**Comment by j2l** [comment]
Hello,
@ToninoTarsi would you please explain how to add "-D wext" to wpa_supplicant ?
I recently run LK8000 on ClaraHD but I miss wifi for GPS and vario data.
