### ISSUE TITLE
LK8000 6.1H task load issue?

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#1112]
I created a task on PG mode using the waypoint file attached (Castelo09) and saved as Test. I clear the task and load it again (without closing the task menu) and LK doesn't show it right away. I need to close and re-open the Task menu to be able to see the task. 

Is this the right behaviour? 

https://drive.google.com/open?id=0B1RFAASTiLubcHZsN01ROXFDQzg

**Comment by ToninoTarsi** [comment]
I can not reproduce.

**Comment by brunotl** [comment]
i know where is the problem, i fix it to night...

**Comment by parapenT1sta** [comment]
@ToninoTarsi DId you create a task using a custom waypoint files? Don't load the file I sent, try to create your own task and follow the steps.

**Comment by brunotl** [comment]
problem is not related to waypoint you use

you just can't load task we have just saved if you don't close task editor dialog fisrst.

**Comment by parapenT1sta** [comment]
@brunotl Thank you for the fix.
