### ISSUE TITLE
Move waypoints in Task Edit (PG optimized or AAT task)

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#1119]
Situation 1 with these Task Settings in System Setup: 
![1](https://user-images.githubusercontent.com/608650/27225089-8f5e546a-5290-11e7-9802-a0bf635d8777.JPG)

Create a task with 3 waypoints, if I move the middle waypoint up to start position or down to finish positon and it doesn't move the radius info, only the waypoint. Is this normal? I thought it should move all the info that we setup while introducing the waypoint in the task.

Situation 2 with these Task Setings in the System Setup:
![2](https://user-images.githubusercontent.com/608650/27225241-31f5b04c-5291-11e7-9068-f25d2ca0f0a0.JPG)

Create a task with 3 waypoints. 
Start: Cylinder, 2Km
Turnpoint: Cylinder, 1Km
Finish: Cylinder, 0.4km

When I move up the finish waypoint to the middle position, it converts the waypoint from Cylinder to Circle ESS even when Sector is defined as "Line" in the system setup.

**Comment by brunotl** [comment]
need refator Start and Finish radius storing for AAT and PG optimized task

**Comment by parapenT1sta** [comment]
@brunotl Does it make sense having Task settings in the system setup because every task is different every day, at least for us paragliding pilots.

What is your opinion about it?

**Comment by brunotl** [comment]
yes it's make sens, because it's unique setting value for default glider task, and it's default value for all other ( AAT or PG Optimized )

**Comment by pventafridda** [comment]
same for gliders. but then every task parameter must be exposed in more 
than one page in task setup.



In data 21 Giugno 2017 4:27:53 PM Sérgio Da Silva 
<notifications@github.com> ha scritto:

**Comment by AlphaLima** [comment]
https://github.com/LK8000/LK8000/issues/1357

**Comment by parapenT1sta** [comment]
@AlphaLima The version you sent me doesn't fix the second situation that I mention here. I am using Paragliding Mode. It doesn't happen all the times and It happens more when I have Optimize Route On.

Create a task with 3 waypoints.
Start: Cylinder, 2Km
Turnpoint: Cylinder, 1Km
Finish: Cylinder, 0.4km

When I move up the finish waypoint to the middle position, it converts the waypoint from Cylinder to Circle ESS even when Sector is defined as "Line" in the system setup.

**Comment by parapenT1sta** [comment]
@AlphaLima Regarding the first situation it's also the same but maybe it's how LK8000 works. It's only changing waypoint ID but not the whole setup (type of waypoint and size) and maybe make senses.

I will close this topic, but just think about the second situation I reported.
