### ISSUE TITLE
Feature Request: Run Aircraft setup after first install/upgrade

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#1127]
Few people setup the device because they don't see GPS fix but forget to setup the aircraft, most of the paraglider pilots complain about IGC fragmented just because they didn't setup Aircraft as Paraglider/Hang Glider.

I think this issue would be fix running Aircraft Setup after first install or after upgrade.

What do you think?

**Comment by ToninoTarsi** [comment]
Difficult to detect in some platform. Better for the pilots to RTFM :-)
