### ISSUE TITLE
Feature Request: Contour lines on map

### ISSUE THREAD

**Issue by pioneer** [LK8000/LK8000#1128]
For E-Ink devices especially, it'd be great to have contour lines on map instead of greyscale colouring, seems it should improve visibility

![_065](https://user-images.githubusercontent.com/200538/28738686-8e581b9e-73fd-11e7-9e21-97ddab9ce4ee.png)

**Comment by pventafridda** [comment]
Contour aka ISO lines can be made out of raster terrain and they should be 
painted like normal topology (shapes).
Furthermore we should then convert each raster map into shapes . Long work.
I did it for my usage 10 years ago on another navigator. Iso lines were 
making the screen very cluttered. I don't think it is a good idea..

**Comment by pioneer** [comment]
Looks not bad on my Kobo, compare with the same on LK8000

![20170730_103450](https://user-images.githubusercontent.com/200538/28751661-323d4d38-7516-11e7-8a5d-e36ef1c9d5d7.jpg)
![20170730_105423](https://user-images.githubusercontent.com/200538/28751666-4080634e-7516-11e7-9389-b9c071172533.jpg)

**Comment by pventafridda** [comment]
looks not bad because you have nothing else painted on. Try painting  
topology lines, glide line and task lines too.

**Comment by cloudsun9** [comment]
Active until maximum selected zoom level would make this a nice feature.
Would be nice to have it.

**Comment by brunotl** [comment]
done

**Comment by cloudsun9** [comment]
Thank you Bruno, this is good.
Might seem fussy but, for e-ink it would be even better as an alternative to the shaded terrain on a white background and (for low lands at least) more lines.
I do appreciate it would be a big effort for a small use case though.
