### ISSUE TITLE
Change feature: Task Time for PG

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#1130]
As far I can see, LK8000 start counting the task time, when you hit the start but I think it should take in count the Start Time set up on the PG Time Gates at least when the Time Gates is setup as 1.

**Comment by parapenT1sta** [comment]
@brunotl Is it possible to be done?

**Comment by ToninoTarsi** [comment]
Agree .. should be fixed !

**Comment by parapenT1sta** [comment]
Thanks 👍
