### ISSUE TITLE
Sound don"t work on all Android device

### ISSUE THREAD

**Issue by brunotl** [LK8000/LK8000#1147]
some user report this issue on Android 7.0
replicated on Nexus 5X Android 8.0

usage of "SoundPool" instead of "MediaPlayer" for play sound seem's solve the problem on Nexus 5X

**Comment by pventafridda** [comment]
Good to know!!


In data 3 Novembre 2017 8:28:44 PM Bruno de Lacheisserie 
<notifications@github.com> ha scritto:
