### ISSUE TITLE
LK8000 PC FullScreen in Distribution package

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#1177]
With more Windows 10 tablets in the market, I think would be a great option deliver an exe file able to run LK8000 in FullScreen. 

We already are able to make LK8000 PC in FullScreen, why aren't we delivering it?

**Comment by pventafridda** [comment]
you can resize already. try


In data 5 Marzo 2018 1:58:28 PM Sérgio Da Silva <notifications@github.com> 
ha scritto:

**Comment by parapenT1sta** [comment]
I know but you still see the "Title Bar". Is a good idea to have it working like Android Phones and tablets.

**Comment by pventafridda** [comment]
nobody using Windows 10 in flight .


In data 5 Marzo 2018 14:33:57 Sérgio Da Silva <notifications@github.com> ha 
scritto:

**Comment by parapenT1sta** [comment]
I know someone from Brazil that was flying with one Windows10 Tablet 😄 But I understand your point of view 👍
