### ISSUE TITLE
(Request) Logbook Details info

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#1184]
I would like to request the info "Distance to Home (Take-Off)".

For us paragliding pilots is good to have the record of the free distance flight (straight line),

**Comment by ToninoTarsi** [comment]
Do you mean a new infobox ?
Because "Distance to home" is always available in multitarget.
Tony

**Comment by parapenT1sta** [comment]
No, my idea is to get this data recorded at the landing on "Logbook Details".
