### ISSUE TITLE
LK8000 miscommunicating ballast with LXNAV S100

### ISSUE THREAD

**Issue by lucaspirola** [LK8000/LK8000#1185]
We're flying a glider with LXNAV S100 and LK8000, with total water of 180L, and when we set the ballast to 100% (180L) in LK8000 the S100 understands as 100% OVERLOAD, which brings the total weight to double the total of the empty glider+pilot.
Am I missing anything here or is this really an issue?  We're using the LXV7 driver.

**Comment by AlphaLima** [comment]
https://github.com/LK8000/LK8000/pull/1294
