### ISSUE TITLE
Field "Live tracker log interval" ignored

### ISSUE THREAD

**Issue by lucasjota** [LK8000/LK8000#1186]
Version 6.1r

When setting the value for "Live tracker log interval" to anything different to "0 sec", it is ignored but keeps sending position every second. This leads to battery drain and data connection overload, specially on LPWAN or slow GPRS.

If bandwidth is insufficient, live tracking servers will show an outdated position, difficulting rescues in case of accident.

**Comment by AlphaLima** [comment]
Already checked with 6.1r an Android (YotaPhone2). Logging Interval works as expeacted. Tested with 1s, 10s and 30s. All work fine.

**Comment by lucasjota** [comment]
Thanks AlphaLima,

I didn't know that bugs must go to lk8000.it
