### ISSUE TITLE
LiveTracking stops

### ISSUE THREAD

**Issue by lucasjota** [LK8000/LK8000#1187]
version 6.1r

Live tracking stops sending messages after 5.33 hours of flight (19044 packets).

WiFi is on, gps status is GPSFix.

After restarting access point and reconnecting WiFi on lk8000, still nothing happens.

Using external tools/devices, access point shows lk8000 (re)associated and tracking server is receiving data correctly.

Is there any way to debug live tracking? any logs?

Best Regards,

Lucas

**Comment by AlphaLima** [comment]
Only if you cmplile a Workbench version.

**Comment by AlphaLima** [comment]
No response,
CAN BE CLOSED!
