### ISSUE TITLE
Android Target API Level 26 required after November 1, 2018

### ISSUE THREAD

**Issue by brunotl** [LK8000/LK8000#1208]

**Comment by ToninoTarsi** [comment]
Yes .. this is an urgent issue to solve. Biside the one that current gradel code does not compile with latest NDK > 17  ( ABIs [armeabi] are not supported for platform. Supported ABIs are [armeabi-v7a, arm64-v8a, x86, x86_64].) .

**Comment by brunotl** [comment]
this problem wil be solved after v7 release because too much change are required ...

**Comment by ToninoTarsi** [comment]
Everything looks fine for me now. Something left ?

**Comment by brunotl** [comment]
it's seem's ndk r18 have "bugge" openmp implementation ( possible conflict with pthread at openmp thread pool creation )

openmp is used for draw terrain and removing them slowdown to much the screen rendering, we need to investigate for right way to solve this problem ...

**Comment by ToninoTarsi** [comment]
Ok. I'm using NDK18.1.506 and do not see any problem.. at the moment.

**Comment by brunotl** [comment]
most of time that work without any issues, but i have experienced few segfault ....

**Comment by brunotl** [comment]
fixed
