### ISSUE TITLE
Multiple vario sources conflict

### ISSUE THREAD

**Issue by elgarrapata** [LK8000/LK8000#1238]
When having more than one device feeding vario I can clearly see LK displaying and processing both sources, instead of considering only the 1st device configured.
My setup:
.Android LK8000
.1st device - IOIO uart GPS module
.2nd device - Bluetooth XCTracer mini II GPS (LK8EX1)
.3rd device - IOIO uart GoFly Picospeed (LK8EX1+PLKAS)

Cheers!

**Comment by AlphaLima** [comment]
Of course,
priotizing is implemented for GPS and Baro only. 
Two varios connected does not make sense.

**Comment by elgarrapata** [comment]
Yes, but the catch here is that I have a device outputting both LK8EX1 and
also PLKAS, and other one with only LK8EX1, which happens to be a better
vario, and I still need that airspeed..

A terça, 2/04/2019, 19:04, AlphaLima <notifications@github.com> escreveu:

**Comment by brunotl** [comment]
workarround  : if you use Generic driver for DeviceC ( GoFly PicoSpeed), you will have aispeed from PLKAS and vario from LK8EX1 will be ignored

**Comment by AlphaLima** [comment]
Normaly the sentences should be configurable in the vario device.
However for the future I'm working on configurable drivers:
https://github.com/LK8000/LK8000/pull/1308
But thats a long way to go!

**Comment by elgarrapata** [comment]
Ok, many thanks. The GoFly alternative config doesn't feature the airspeed.

A terça, 2/04/2019, 19:37, AlphaLima <notifications@github.com> escreveu:
