### ISSUE TITLE
LK8000 with Bluefly TTL_v11

### ISSUE THREAD

**Issue by alexandre-pereira** [LK8000/LK8000#1302]
Hello,

Just tried to update my version 6.00B of LK8000 to 7.0 (latest) and I actually have a lot of issues with the GPS in the app displaying "GPS NO VALID FIX" sometimes (not all the time) during a flight, cutting my IGC tracklogs in multiple files (I also checked those files and they are sometimes under ground level).
It also takes a long time to find a GPS fix, and sometimes doesn't find any at all, even if in a clear zone.

I tried multiple configs (LX something in Device A setup, Blueflyvario as well, same with the baudrates etc), nothing worked.

I went back to 6.00B and everything worked as expected again.

Config : KOBO MINI + BLUEFLYVARIO/GPS V11TTL (linked directly, no bluetooth nor wifi)

Maybe is that the V11 TTL version of the Bluefly vario is not supported anymore by LK8000?

Thanks for the infos,
Alex

**Comment by brunotl** [comment]
V11 TTL version of the Bluefly vario is supported.

can you do a NMEA Log with v7 and send it to me with Runtime.Log and IGC files?

thanks.

**Comment by alexandre-pereira** [comment]
[NMEA_2080-01-06-00-00-29.txt](https://github.com/LK8000/LK8000/files/3008159/NMEA_2080-01-06-00-00-29.txt)

**Comment by alexandre-pereira** [comment]
[2019-03-22-XLK-PEN 1 TO 24.zip](https://github.com/LK8000/LK8000/files/3008160/2019-03-22-XLK-PEN.1.TO.24.zip)
(During a 100km flight, didn't had NMEA log ON on this one but same bug, don't know if it helps)

**Comment by brunotl** [comment]
can you sent to me your RUNTIME.log
your "2029-03-22.." log are very surprising because it's seem's each part end with landing detection ...

PS : we can continue by mail in french if you want...

**Comment by alexandre-pereira** [comment]
[RUNTIME.log](https://github.com/LK8000/LK8000/files/3009658/RUNTIME.log)

Here you go :) As you want, I'll send you my email, you can call me as well if you need more infos. Maybe it's faster and better for communication.

**Comment by brunotl** [comment]
evrything lokk good in your runtime log but it only contains v6.0b run, so no surprise...

**Comment by villamany** [comment]
What firmware do you have on the Bluefly borad?
And what speed are you using on the kobo?

**Comment by alexandre-pereira** [comment]
Found the problem.
"Aircraft Setup" was on "Glider" and not "Paraglider/Hangglider", and I was using the barometric altitude, it was a high pressure day, so my track was under the ground due to a bad calibration. That's why I got so many tracks.
