### ISSUE TITLE
Is possible to use wifi on the kobo? 

### ISSUE THREAD

**Issue by villamany** [LK8000/LK8000#1355]
Is possible to use the kobo wifi to send tracks to xcontest for example?

**Comment by brunotl** [comment]
Duplicated : #1097

**Comment by j2l** [comment]
I'd also need wifi setup (beyond the ON/OFF button), since GPS and vario NMEA messages are sent over TCP in my case.
It works on Android, but not on Kobo.

**Comment by brunotl** [comment]
wifi setup must be done in Nickel (the original kobo software )

**Comment by j2l** [comment]
Thank you @brunotl I'll try that with Condor.
