### ISSUE TITLE
Map orientation - North on top

### ISSUE THREAD

**Issue by scls19fr** [LK8000/LK8000#1376]
Hello,

I'm new to LK8000, I have read documentation (at least partially) but I haven't found a way to have map orientation with North on top.
It will be great if clicking on North direction icon (at screen top right) could change map orientation mode.

Kind regards

**Comment by scls19fr** [comment]
I have found this setting in MENU / Display 2/3 / Map Orient / North Up
but clicking on North icon to change it could be an interesting feature to have.

**Comment by AlphaLima** [comment]
Please use the LK8000 Forum for such beginners questions. GIT is for developers only!
https://www.postfrontal.com/forum/default.asp?CAT_ID=11
Search for "Custom Key"
