### ISSUE TITLE
Onyx Boox T68 support

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#1398]
Is or will be the Onyx Boox T68  supported by LK8000 for A1 fast mode?

I know there is two firmware version where the ID of the device is different but still the same hardware. I can share some info of mine device if you want to add the ID.

**Comment by brunotl** [comment]
we need Product name, you can get it using this app 
https://play.google.com/store/apps/details?id=com.dev.deviceinfo

**Comment by parapenT1sta** [comment]
> we need Product name, you can get it using this app
> https://play.google.com/store/apps/details?id=com.dev.deviceinfo

Sent by e-mail :)

**Comment by brunotl** [comment]
this device is Android 4.0.4 ( API 15) , min API level supported is API 16
