### ISSUE TITLE
LK8000 unstable with new Kobo Mini Update

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#1403]
Just to want to give som feedback about the new Kobo Mini update and LK8000.

LK8000 works but when pressing on the screen nothing happens after some time of running it but with LK8000 OTG version works perfectly fine. Maybe the kernel version on LK8000 OTG version is more stable.

**Comment by brunotl** [comment]
unable to replicate.
last Kobo Mini firmware is  3.19.5761-s released 4 year ago.
kernel version is in RUTIME.log, so please add all kernel version you have tested in this issues.

**Comment by parapenT1sta** [comment]
I will check it and share it here.
