### ISSUE TITLE
Support OpenAIP airports, airspace... format

### ISSUE THREAD

**Issue by scls19fr** [LK8000/LK8000#1415]
Hello,

[openAIP](http://www.openaip.net/) is a web-based crowd-sourced aeronautical information platform which deliver free, current and precise navigational data to anyone.
Supporting their file formats could be a nice improvement (especially airports format).

See http://www.openaip.net/downloads for documentation
http://www.openaip.net/system/files/openAIP_aip_format_1_1_airport.pdf
http://www.openaip.net/system/files/Airspace.pdf
http://www.openaip.net/system/files/openAIP_aip_format_1_1_navaid.pdf
http://www.openaip.net/system/files/openAIP_aip_format_1_1_hotspot.pdf

Kind regards

PS : similar issue https://github.com/XCSoar/XCSoar/issues/355

**Comment by brunotl** [comment]
already supported, was added 4 years ago ...

just a tips : careful about OpenAIP airspaces data, it's not official data, it contains lot of error ... ...

**Comment by scls19fr** [comment]
Sorry about that.
Are airports aip data also supported?

**Comment by AlphaLima** [comment]
You obviously don't test it yourself!
Yes! However for Waypoints OpenAIP also offers CUP Files.

**Comment by scls19fr** [comment]
aip data for airports provide much more information than in cup file.

**Comment by AlphaLima** [comment]
We already support OpenAIP for airspaces and Waypoints!!!!
You obviously have not tested it yourself nor work with it.
What are you missing and what is your intension???

**Comment by scls19fr** [comment]
Thanks for your welcoming help. It works as advertised... maybe adding runway width should be considered.
I think airports data should be considered differently than simple waypoint and a priority between waypoint data and airport data should be set ie if a waypoint and an airport are closer than 200m only airport should be displayed.

**Comment by brunotl** [comment]
- runaway dir and length are already handled 
- turnpoint declutering order is another subject, so open another issues for that.

**Comment by scls19fr** [comment]
dir and length are perfectly... Not width which is an available data.

I will open an other issue about turnpoint declutering order

**Comment by scls19fr** [comment]
Supporting at least 3 waypoints files will be also a great feature to have.
One for airports one for national turnpoints (France.cup for example) and a last one for personal turnpoints.
Such waypoints organisation will simplify updating data without hassle.

**Comment by brunotl** [comment]
please test the last beta...

**Comment by scls19fr** [comment]
Thanks for the tip...
9 waypoints is enough!
