### ISSUE TITLE
GPS: NO VALID FIX with LK8000-beta 7.1k (Feb 25 2020)

### ISSUE THREAD

**Issue by scls19fr** [LK8000/LK8000#1416]
Hello,

I'm trying LK8000 beta but I see "GPS: NO VALID FIX" on map
and position is not updated.

I compared my settings between LK8000 stable and beta and couldn't find what is wrong.

FLY / MENU / Config / Config 2/3 / LK8000 Setup / Device Setup

Device configuration A
Name: Internal
Status: nothing with beta but GPSFix with stable version (7.0 Oct 26 2018)
Geoid Altitude: ON
Serial mode: Normal
Device model: Generic

When I click on Terminal button I see some text which is updating with beta version... strangely when I click on Terminal button with stable version I see "NO DATA RECEIVED" while position is updating correctly at startup!

Hardware: smartphone Huawei P30 Lite
OS: Android 9 with EMUI 9.1.0

Any idea?

Kind regards

**Comment by scls19fr** [comment]
I also tried to rename `_Configuration_beta` to `_Configuration_beta_old` to force creation of new config file but same problem "GPS: NO VALID FIX" occured

**Comment by brunotl** [comment]
you need to check GGA and RMC sentence  : http://aprs.gids.nl/nmea/#gga

to make NMEA log, use  "menu" -> "Config 2/3" -> "NMEA Logger"
log is writed in folder "LK8000/_Logger",  file name pattern is : "NMEA_YYYY-MM-DD-hh-mm-ss.txt"

**Comment by brunotl** [comment]
another tips to avoid "NO VALID FIX" : go outside, GPS is not made for indoor location...

**Comment by scls19fr** [comment]
Why it could work with stable version and not with beta?

**Comment by brunotl** [comment]
- stable version use android "LocationListener" (depending of device but can be a fused location).
- last beta use only GPS.

**Comment by scls19fr** [comment]
ok I will go outside (when weather) will be better and will reopen this issue if it's still failing.
Sorry.

**Comment by AlphaLima** [comment]
![image](https://user-images.githubusercontent.com/1188401/75706607-bd234100-5cbd-11ea-84cb-27a212148e8e.png)

**Comment by AlphaLima** [comment]
![image](https://user-images.githubusercontent.com/1188401/75706832-24d98c00-5cbe-11ea-9db9-4aa81e40bfbe.png)
