### ISSUE TITLE
Sunset

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#1417]
Is it possible to make Sunset option available again for Infopages/Bottom bar?

**Comment by brunotl** [comment]
sunset is available in waypoint details, and was never available elsewhere...

where you want display sunset and for what position ?

**Comment by parapenT1sta** [comment]
I thought that was available before on the bottom bars.
Basically It can be used to know that we must land 30 minutes maximium past that time if we want to get FAI to validade our flight, aren't the FAI rules for VFR?

**Comment by parapenT1sta** [comment]
I think it's done! :-) Thanks Bruno.
