### ISSUE TITLE
[Proposal] waypoint display GR + arrival altitude

### ISSUE THREAD

**Issue by bobmorane06** [LK8000/LK8000#1454]
Hello community, although last time that I coded was in 1996 (!), I decided to try to clone LK8000 and add a feature that I was missing in LK8000. 

I added a new Waypoint display mode with glide ratio required *and* arrival altitude with the format “WaypointName : GR/AltArrival”. 

The reason behind the feature is that I find it safer to make my in-flight navigation decisions based on GR (eg I decide not to go further than GR 20 from the closest landable on a glider with theoretical L/D of 40), but the arrival altitude adds confidence. Today it’s one or the other so I added an entry to "Landable value" in menu "11 Appearance".
 
![LK8000_GR_AltArr](https://user-images.githubusercontent.com/61326036/83296133-8099af80-a1f0-11ea-9957-1c6962b43faf.jpg)

I still have a tweak to add to the code, then I’ll do my best to create a Pull Request this weekend (I’m still struggling with git), assuming you think it makes sense to add my change.

**Comment by brunotl** [comment]
do a draft pullrequest with your change, like that we can do a code review ...

**Comment by bobmorane06** [comment]
Done, it was tedious and I hope I did it right :-) 

I wasn't too sure of coding style and the use of tabs and/or spaces, I tried to mimic the existing code
