### ISSUE TITLE
Multimap : Map scale & Overlay overlaps

### ISSUE THREAD

**Issue by brunotl** [LK8000/LK8000#1518]
Landscape display orientation, on Multimap1, 2 and 4, the map scale indicator and the Right Lower Overlay value became overlapped when the side view height is reduced to zero, while of course it does not happen on the Main Map page.

https://drive.google.com/file/d/12Ssc_oIQCLUQOpZj4vZaqi6XeQ10NlTl/view?usp=sharing

> https://www.postfrontal.com/forum/topic.asp?TOPIC_ID=9181

**Comment by AlphaLima** [comment]
fixed 
https://github.com/LK8000/LK8000/pull/1520
