### ISSUE TITLE
Serial ports Kobo to support OGN and FANET

### ISSUE THREAD

**Issue by parahooners** [LK8000/LK8000#1542]
Evening all,

This may have already be asked or info out there apologies in advance if so....

Im trying to wire 2 no TTGO Tbeams to the KOBO to support OGN and FANET is it possible to use 2 different serial ports..

Iv tried wiring up to the others and the Kobo either freezes or the touch screen is unresponsive

Reason for using 2 TTGO is to aid visual awareness where I fly as its a mix of OGN and FLARM FANET...

**Comment by brunotl** [comment]
only one serial port are usable for external device on Kobo.

**Comment by parahooners** [comment]
@brunotl thanks for getting back its appreciated
