### ISSUE TITLE
Copyright violation by using the proprietary OnyxAndroidSDK

### ISSUE THREAD

**Issue by MaxKellermann** [LK8000/LK8000#1545]
LK8000 is a combined work of GPL code and the OnyxAndroidSDK (https://github.com/androidli/OnyxAndroidSDK/). The latter is proprietary; it is **not** open source or free software, not compatible with any GPL version. Combining this with GPL software constitutes a copyright violation of my work.

Unlike https://github.com/LK8000/LK8000/issues/1544, this cannot be fixed; you must cease distributing and using the OnyxAndroidSDK.
Until then, all builds of LK8000 with the OnyxAndroidSDK are illegal, and your license to use XCSoar code has been terminated.

**Comment by brunotl** [comment]
Closed by commit 3a6636a
