### ISSUE TITLE
Change maximum waypoint radius admited on LK8000 from 100Km to as is possile

### ISSUE THREAD

**Issue by Mrapari** [LK8000/LK8000#1550]
During last Italian campionship I've seen that the maximum waypoint radius admited on LK8000 is 100Km, and for this reason I couldn't use LK because some waypoints radius on task competition was upper 100Km. I think it is easy to solve and I'll be very gratefull if it will done. Thanks so much

**Comment by AlphaLima** [comment]
what version are you you using?
with the latest beta 7.3.8, I don't have any radius limitation, not in normal sectors nor cylindwers.
Testet for normal and AAT Tasks.

![image](https://user-images.githubusercontent.com/1188401/127813875-67e81da6-8d89-4d01-89a4-753a2dc73bcc.png)

**Comment by Mrapari** [comment]
Ho, the problem is shown only for the start point. The other seems to be goodIl 2 Ago 2021 08:29, AlphaLima ***@***.***> ha scritto:
what version are you you using?
with the latest beta 7.3.8, I don't have any radius limitation, not in normal sectors nor cylindwers.
Testet for normal and AAT Tasks.

**Comment by AlphaLima** [comment]
A start radius > 100km ???
(Does not make sense to me)

**Comment by Mrapari** [comment]
I don't know the sense, but it was in the last Italian champions. And for that reason I can't use LK8000 for that tasksIl 2 Ago 2021 09:57, AlphaLima ***@***.***> ha scritto:
A start radius > 100km ???
(Does not make sense to me)

**Comment by brunotl** [comment]
> I don't know the sense, but it was in the last Italian champions. And for that reason I can't use LK8000 for that tasks

can you share the task details ?

**Comment by Mrapari** [comment]
Here one of the task planned on xctrack..Il 2 Ago 2021 11:29, Bruno de Lacheisserie ***@***.***> ha scritto:

I don't know the sense, but it was in the last Italian champions. And for that reason I can't use LK8000 for that tasks

can you share the task details ?

**Comment by brunotl** [comment]
> Here one of the task planned on xctrack..

where is the task ?

**Comment by Mrapari** [comment]
File attached in the previous mailIl 2 Ago 2021 13:42, Bruno de Lacheisserie ***@***.***> ha scritto:

Here one of the task planned on xctrack..

where is the task ?

**Comment by brunotl** [comment]
no attachement in github issues comments ...

**Comment by Mrapari** [comment]
Sorry I've attached in the mail. but now added also on this post
![Screenshot_20210802-130136_XCTrack](https://user-images.githubusercontent.com/10142975/127880871-dbbcc3f4-fd9e-41fe-ab35-648475bf10be.jpg)
![Screenshot_20210802-130118_XCTrack](https://user-images.githubusercontent.com/10142975/127880874-de4824ba-34cb-4e92-b8f7-0839cc5c7b0b.jpg)

**Comment by Mrapari** [comment]
Also a waypoint file if it is necessary..
[Trofeo 100 Laghi.zip](https://github.com/LK8000/LK8000/files/6917817/Trofeo.100.Laghi.zip)

**Comment by brunotl** [comment]
tips : if task is loaded from xctrack tsk file or QRCode, radius are right still you don't edit the turn point.

**Comment by brunotl** [comment]
Closed by commit 6a9cb9b56003d38835e600c08207d42096b6d858

**Comment by Mrapari** [comment]
Yes, but it isn't the better way to do competition. Frequently the tasks can be varied during and after the breefing...
