### ISSUE TITLE
Global  support of "Enter" and "ESC" on all HID

### ISSUE THREAD

**Issue by XCNav** [LK8000/LK8000#1558]
Depending of the choosen Keyboard there is no definite Button for "ENTER" or "ESC"
For example with Keyboard 2 selected "B" triggers Enter in Menus an PAN Mode, but also zooms out in default pages.
"Escape" function has now to be defined for each function to return to default mode via .xci file as there is no global support of ESC. So for establishing a true remote controll you would need these 2 functions.

**Comment by brunotl** [comment]
refactored in commit 8d0fa38396920a421d83cc52fa1b010c9095559a 8d0fa38396920a421d83cc52fa1b010c9095559a b6c7a5e847c966d06859351bdbcc4b390609e0ef
