### ISSUE TITLE
Run LK8000 on Raspberry PI4 and Raspberry PI3

### ISSUE THREAD

**Issue by urb31075** [LK8000/LK8000#1559]
I compiled from source LK8000 on Paspberry Pi 4. I start it and everything works great.  I tried compiling to Raspberry Pi 3.  The program started without errors, but the buttons on the front panel are not displayed.
![LK8000_RP3](https://user-images.githubusercontent.com/25562163/148595200-da2e9f10-e57c-43a7-8c4b-e1ab71c62db3.png)

**Comment by urb31075** [comment]
[RUNTIME.log](https://github.com/LK8000/LK8000/files/7830855/RUNTIME.log)

**Comment by urb31075** [comment]
I compile on Raspberry Pi 3 with: 
make TARGET=LINUX DEBUG=y
make install DEBUG=y

On start i see:

LK8000-LINUX_debug: Common/Source/xcs/Screen/OpenGL/Canvas.cpp:717: const PixelSize Canvas::CalcTextSize(const TCHAR*) const: Assertion `font' failed.
Aborted

**Comment by brunotl** [comment]
what is linux distribution ?

assert is about missing font, font needed is "ttf-dejavu", available in different place depending of linux distribution and not automatically installed by default.

list of known font are here : https://github.com/LK8000/LK8000/blob/983f2974ecd9120f4ba05f050b435e8e261cf36f/Common/Source/xcs/Screen/Custom/Files.cpp

**Comment by urb31075** [comment]
1) ...what is linux distribution ? ...

I install OS in three steps
 - uploaded and written to the microsd image Raspberry Pi OS Lite (Release date: October 30th 2021)
   from https://www.raspberrypi.com/software/operating-systems/
 - configuring the system
 - Install the graphical shell with the command sudo apt install raspberrypi-ui-mods

This makes it possible to install a desktop raspbian without a lot of unnecessary programs.

2) Unfortunately, this installation method did not install the required fonts.

installing the fonts by the command:  sudo apt-get install fonts-dejavu solved my problems


I sincerely thank you for your help
