### ISSUE TITLE
Font resize is broken on Linux - LK8000 crash on startup

### ISSUE THREAD

**Issue by hm1702** [LK8000/LK8000#1570]
Font size calculation produces wrong sizes
```
void ApplyCustomResize(LOGFONT *logfont, short change) {
if (change != MAXFONTRESIZE) {
    int f = change - MAXFONTRESIZE;
    logfont->lfHeight += logfont->lfHeight * f / 16;
  }
}
```
`logfont->lfHeight` is declared as unsigned int,  `f` is declared as int. Thus in the calculation above `f` is interpreted as an unsigned int which gives a really huge value for negative values of `f`

![grafik](https://user-images.githubusercontent.com/98644926/152528585-23d0285b-0559-4cb1-91f5-c8d4ce5f3667.png)

LOGFONT is declared in wingdi.h

**Comment by brunotl** [comment]
right ! due to integer promtions rules : 
> If the unsigned type has conversion rank greater than or equal to the rank of the signed type, then the operand with the signed type is implicitly converted to the unsigned type.

on windows, the five 5 member of LOGFONT are defined as long ...

2 option to fix the problem : 
 - change LOGFONT members to int
 - add explicit cast in function ApplyCustomResize

...

**Comment by hm1702** [comment]
I would propose a cast as font sizes are positive by nature. Changing LOGFONT may have other side effects.

**Comment by brunotl** [comment]
ok, can you do a pullrequest with the fix ?

**Comment by hm1702** [comment]
see https://github.com/LK8000/LK8000/commit/a342e1c78f09ab967ef983b379cfec680e8f02ba
