### ISSUE TITLE
KMAPS files stored in wrong location

### ISSUE THREAD

**Issue by bobmorane06** [LK8000/LK8000#1584]
Environment:
- LK8000 7.3.14 for Android
- LKMAPS v1.7 (Android / app info)
- Xiaomi Redmi Note 9s, Android 11

Scenario:
- Config / LK8000 setup / System Setup / 1 Site / Open LKMAPS / Configurations / data.fln

The file is saved in /storage/emulated/0/LK8000/_Configuration  and not in /storage/emulated/0/Android/data/org.lk8000.test/files/_Configuration

Same for other files loaded from LKMAPS (I tried V2_INTERNAL.dvc and one airspace in Africa)

**Comment by brunotl** [comment]
LKMAPS only work for current stable version, ( 7.2.1 )  and must be rewrited inside LK8000 for  current beta and next stable version...
