### ISSUE TITLE
AAT task via QRCode

### ISSUE THREAD

**Issue by mzeddd** [LK8000/LK8000#1589]
Hello,

Is it possible to load AAT tasks via QRCode?
I don't see AAT tasks descrtiption in XCTrack file format https://xctrack.org/Competition_Interfaces.html
Is it possible to set max start and min finish altitude in it?

Are you going to extand this format for gliders?

Thanks in advance,
Valery

**Comment by brunotl** [comment]
LK8000 only read xctrack task file or qrcode, so you need to ask to who produce this type of file or qrcode.
