### ISSUE TITLE
Suggestion:- Add aAlt to Bottom Bar Customising Options

### ISSUE THREAD

**Issue by JBlyth** [LK8000/LK8000#1593]
When flying a fleet of gliders where pilots use Metres or Feet for Altitude, it would be useful to be able to add aAlt to the bottom menu bar so it is easy to give a quick Altitude Report over the radio in either measurement, particularly when thermalling.

The Alt2 Bottom Bar does show aAlt, but I can't see any way of customising the other bottom bars to include aAlt.

Many thanks
John in Sunny Carnarvon, Western Australia

**Comment by brunotl** [comment]
already available, it's named "Altern QNH"
