### ISSUE TITLE
Wiki Linux section needs an small update

### ISSUE THREAD

**Issue by JBlyth** [LK8000/LK8000#1595]
I have just been installing Linux via WSL2, and I noticed the install command in the LK8000 Wiki included **ttf-dejavu**. I found that this caused an error as the name seems to have been changed to **font-dejavu**.

So I think section "Install all the necessary tools" should read:-
sudo apt-get install build-essential pkg-config libsdl2-dev libsdl2-mixer-dev libzzip-dev libboost-dev libfreetype6-dev libpng-dev libgeographic-dev xsltproc imagemagick **fonts-dejavu** zip libgl1-mesa-dev libegl1-mesa-dev libx11-dev libasound2-dev libsndfile1-dev

See https://www.reddit.com/r/Ubuntu/comments/kjyjov/cant_install_ttfdejavu_and_ttfliberation/ for more information.

Cheers
John in Sunny Carnarvon - Western Australia

**Comment by brunotl** [comment]
right, "ttf-dejavu" transitional dummy package was removed since debian 11 (bullseye)
