### ISSUE TITLE
7.4.1. Optimization for cylinders over 100 km does not work

### ISSUE THREAD

**Issue by mymyser123** [LK8000/LK8000#1607]
Optimization for cylinders over 100 km does not work. The optimization line goes not to the border of the cylinder, but to its center, for example, if you are already inside the cylinder at the previous TP and you need to fly to the exit .. The total length of the distance is also incorrectly calculated.

**Comment by brunotl** [comment]
Please add the task file to the ticket...

**Comment by brunotl** [comment]
tested, work perfect ...

![image](https://user-images.githubusercontent.com/858626/220204527-9285aa6a-dff8-499e-a2f9-86e1fcff4a37.png)

**Comment by mymyser123** [comment]
[TASK-EX.zip](https://github.com/LK8000/LK8000/files/10790805/TASK-EX.zip)
![photo_2023-02-21_10-32-56](https://user-images.githubusercontent.com/125807439/220278432-66bf5b95-5a8e-4348-9fa9-2cfaeb7a8b50.jpg)
![photo_2023-02-21_10-32-51](https://user-images.githubusercontent.com/125807439/220278448-6f8dfa36-55d7-47d0-9093-4e5abeebf320.jpg)

**Comment by brunotl** [comment]
when task optimizer is not disabled : 
![image](https://user-images.githubusercontent.com/858626/220291918-6848605a-6269-45a8-a2cf-08c2d09bedde.png)

that work perfectly
![image](https://user-images.githubusercontent.com/858626/220290340-e41957b1-b108-4647-bbd0-3fa110a352aa.png)
