### ISSUE TITLE
Battery voltage not available with recent Kobo Nia

### ISSUE THREAD

**Issue by SolidRick** [LK8000/LK8000#1615]
Hello,
only with recent Kobo Nia units (year 2023), battery voltage is not available, this is quite annoying.
Apart from that, everything works fine, Kobo Nia is definitively the best e-reader option at the moment

![NoBattery](https://user-images.githubusercontent.com/62525519/236671154-6059ee32-3e1a-46bc-993b-a912cc0be884.jpg)

**Comment by brunotl** [comment]
fixed
