### ISSUE TITLE
Radio device support: AIR Control Display

### ISSUE THREAD

**Issue by amagnolo** [LK8000/LK8000#1619]
Please implement support for [AIR Control Display](https://www.air-avionics.com/?page_id=178) radio in LK8000.

The NMEA protocol is specified in chapter "Serial Control Interface" of the [installation manual](https://www.air-avionics.com/?wpdmpro=air-control-display-57-installationshandbuch) and should be rather straightforward to implement.

This device has been supported by XCSoar since a few years.

**Comment by brunotl** [comment]
WIP : commit  aa5a69623384aa9ad2e8291f4a0228000b8fd128
