### ISSUE TITLE
Focus on window not working in config correctly

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#576]
Linux version. Simulate. Directly go to System setup, and for example enter page13, try to change Screen Data. When you click to change to half overlays you will not get the choice selected and be back to list of choices . If you click on Help instead of Half overlays, then you will be able to select half overlays, the focus been working.

**Comment by brunotl** [comment]
focused & selected are two different concept !

List Item highlight are focus, so only painted when parent (list) have focus and of course, selection is not visible if list don't have focus.
 - on enter : focus are on Select button (first child control )
 - after close helps : focus are on Help Button ( focused by click )

we need to add "Selected item highlight" concept, for avoid this kinds of mistake.

I'll do that to Night.

**Comment by pventafridda** [comment]
Thanks, that’s what I meant. The Selected item is already in use, it just does not work in such case for the dialogs when started up. Sort of..

**Comment by brunotl** [comment]
fixed
