### ISSUE TITLE
Position of LK on Linux desktop screen totally random on startup

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#582]

**Comment by brunotl** [comment]
no bug, cf. SDL Doc : 

_Note 2: If you want to control the position on the screen when creating a windowed surface, you may do so by setting the environment variables SDL_VIDEO_CENTERED=center or SDL_VIDEO_WINDOW_POS=x,y_

**Comment by pventafridda** [comment]
Maybe a setenv from lk will solve it. Thx
---
Sent from mobile



Il 25 Agosto 2015 14:39:06 Bruno de Lacheisserie <notifications@github.com> 
ha scritto:

**Comment by brunotl** [comment]
loose of time ...

**Comment by pventafridda** [comment]
Loose of time, closing.
