### ISSUE TITLE
BlueFlyVario not working on Kobo version

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#589]
Same settings were used on XCSoar and it worked: http://www.paraglidingforum.com/viewtopic.php?p=p449428#p449428
![10998274_10153112897065680_1804172455_o](https://cloud.githubusercontent.com/assets/608650/6321835/1b46db38-bad5-11e4-90e3-420856684903.jpg)

**Comment by nikvaliris** [comment]
As a suggestion it could be an issued with the baud rate.

The Bluefly TTL v8 has a UART2 set-up as default as follows: 
Baud Rate: 57600
Data Bits: 8
Stop Bits: 1
Parity: No Parity
Flow Control: None

The NMEA output from LK8000 on the Kobo is showing scrambled data so LK8000 may not be reading the Baud rate setting correctly on the config page when selecting 57600.  Unfortunately I couldn't set the UART2 to 9600 to test it as only the Bluefly v9 (not v8) and above are the only models that support changes to UART2 baud rate from the default 57600.
