### ISSUE TITLE
Kobo: IGC send file is available and makes LK crash

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#591]
Menu > Info 2/2 > LogBook > IGC Send file > ... crash.

Solution? Make it not available for Kobos?

**Comment by brunotl** [comment]
not implemented in kob & linux, I will fix crash.

**Comment by SergioDaSilva82** [comment]
Thanks!

**Comment by pventafridda** [comment]
It is a problem in Linux, not limited to Kobo. The title of this issue was misleading. I have opened another one.
