### ISSUE TITLE
Sound error ALSA lib

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#596]
during runtime we often get  ALSI lib pcm.c 7339 snd_pcm_recover  underrun occured.

**Comment by brunotl** [comment]
problem is known, is in AlsaLib, install "pulseaudio" package solve the problem.

**Comment by pventafridda** [comment]
Is it related to the PC version also? Because on PC there are problems with sounds on startup, there is a lock or hang pending..

**Comment by brunotl** [comment]
Alsa on PC ?
- on Windows platform, we use win32 "sndPlaySound" API 
https://msdn.microsoft.com/en-us/library/windows/desktop/dd798676%28v=vs.85%29.aspx

- on Linux we Use SDL_Mixer 
http://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html

**Comment by pventafridda** [comment]
For this reason I asked. Because we have a problem on PC, on startup the sound is muted, and the clockwork is running, and I have seen some crashes.

**Comment by pventafridda** [comment]
pulseaudio was installed on linux nimbus, the ALSA lib underrun error is always occurring.

**Comment by pventafridda** [comment]
it disappeared automagically. mistery
