### ISSUE TITLE
Terrain Shading artefact

### ISSUE THREAD

**Issue by brunotl** [LK8000/LK8000#598]
- Terrain Slope calculation are wrong on right border of screen.
- also wrong on border on top/right border of terrain data (DEM file)

PS : more or less visible, depends of Screen resolution, huge on 300*400.

**Comment by pventafridda** [comment]
I cannot confirm this. Testing on Linux 400x300, demo terrain, no problems.


From: Bruno de Lacheisserie 
Sent: Wednesday, February 25, 2015 11:05 AM
To: LK8000/LK8000 
Subject: [LK8000] Terrain Shading artefact (#598)

  a.. Terrain Slope calculation are wrong on right border of screen. 
  b.. also wrong on border on top/right border of terrain data (DEM file) 
PS : more or less visible, depends of Screen resolution, huge on 300*400.

**Comment by brunotl** [comment]
400x300 is not same as 300x400

| V5.0 with Shading     | V5.0 without Shading     |
| ------------- |:-------------:|
| ![image](https://cloud.githubusercontent.com/assets/858626/6380223/55c39de0-bd38-11e4-87a8-c49182673a31.png)      | ![image](https://cloud.githubusercontent.com/assets/858626/6380206/42be07ee-bd38-11e4-810b-789e34572545.png)             |

**Comment by pventafridda** [comment]
Ok now I can see it in my linux too. But with light terrain it is quite hard to see it
