### ISSUE TITLE
Fonts linux-pc problem..

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#606]
Example  480x272  dlgStartup.cpp using LK8MapFont , which is 
propGetFontSettingsFromString(TEXT("20,0,0,0,400,0,0,0,0,0,0,3,2,Tahoma"), &logfontMap);

but on Linux the vertical size (height) of the font generated is not the same as on PC.
Font is bigger in fact on linux.

**Comment by brunotl** [comment]
font is Tahoma on PC and PNA, not on linux ...
for know what font is used on linux, look "Common/Source/xcs/Screen/Custom/Files.cpp"

**Comment by pventafridda** [comment]
I know very well that Tahoma fonts belong to Microsoft and are not used in Linux.
What I am saying is that it happens that the font we are using are not matching the desired size.
If we ask for a font size 20 , like in the example, we expect 20 not 21.

**Comment by pventafridda** [comment]
I am wrong. 
You are right. Closing.
