### ISSUE TITLE
Kobo: change Empty Map color to White as default.

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#610]
Having white as default looks much better...

**Comment by brunotl** [comment]
only for B&W dithered device

**Comment by SergioDaSilva82** [comment]
That is why I put Kobo in the title :)

**Comment by pventafridda** [comment]
What if we create a device, like for Mio, Hp etc.?
Either we have embedded ifdef KOBO or we do like that.
Adding a device is much easier. All peculiar things belonging to kobo will be set that way.
I think that setting white background is not a problem for users, with or without kobo.

**Comment by SergioDaSilva82** [comment]
I agree that white for everyone won't be a problem. The fact is the LCD Green is not good for kobos.

**Comment by pventafridda** [comment]
I confirm KOBO is a define., so we can put it at once

**Comment by brunotl** [comment]
KOBO device is not the right way
Use isDithered() instead

**Comment by pventafridda** [comment]
seen late. good idea thanks i correct it
