### ISSUE TITLE
10Hz variometer bar refresh rate & 1Hz screen refresh rate (LK8000 6.0?)

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#612]
Some pilots are requesting higher refresh rate for variometer bar 10Hz.

http://www.postfrontal.com/forum/topic.asp?TOPIC_ID=7702

**Comment by brunotl** [comment]
when we fly, we look outside, so it's useless ...

**Comment by pventafridda** [comment]
that was the idea, in fact! (to look outside)

**Comment by SergioDaSilva82** [comment]
Paolo, so is better to close it.

**Comment by lshachar** [comment]
The on screen variometer is the only place where I get the actual vario value when I'm flying. I have a no screen vario and lk8000 is the only display I'm using. to me, this is more than useful, it is critical to have a much faster vario display. (personally I'm not using the bar, but only the numerical vario value)
(I got here from [this thread](http://www.postfrontal.com/forum/topic.asp?TOPIC_ID=7702) in postfrontal)

**Comment by villamany** [comment]
It is important for me also, i would like to have a more responsive visual vario display (both vario bar and vario value overlay)
