### ISSUE TITLE
IsDithered mode: Optimization for FAI triangle display

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#616]
"For the FAI traingles I will appriciate change of the colour, traingles are barelly visible."

" on the map it can be hard to see due to the original colours translating to very faint grey shades."

http://www.paraglidingforum.com/viewtopic.php?p=p450587#p450587

**Comment by polachp** [comment]
That is absolutely true!

**Comment by pventafridda** [comment]
I can make them darker of course. But pity we cannot make them different. Maybe it is not a problem though.

**Comment by SergioDaSilva82** [comment]
https://github.com/LK8000/LK8000/commit/591a72d8f1336a059a4ca070c6a05afcd26e6868

maybe can be optimized in the future but is much better right now.
