### ISSUE TITLE
IsDithered mode: Bottom bar opacity at 100%

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#617]
I am getting feedback about the bottom bar being at 75%, after a while is hard to read the values because the "ghost" effect.

At 100% looks much better.

Just a suggestion to put bottom bar at 100% as default in "IsDithered" (Kobo) mode.

**Comment by pventafridda** [comment]
I have done it. But now please lets focus on bugs. There are tons of glitches and problems to check and fix.
