### ISSUE TITLE
Logbook: bitmaps error

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#619]
The scrolling cursor for the scroll bar has no bitmaps (or bitmaps are painted elsewhere?) on PC .
Test: on PC  Config - Setup Basic - Efficiency  has no scroll bar bitmaps.

**Comment by pventafridda** [comment]
Bitmaps are not initialized correctly all the times. It looks like something wrong is going on randomly.

**Comment by SergioDaSilva82** [comment]
I had the same issue, I notice that happened to me when I copy the whole LK8000 folder from LINUX to the PC. but if I just copy the .exe file and the language folder over the LK8000 5.0a folder it works properly.

**Comment by pventafridda** [comment]
Ah! You mean I am experiencing a config error!! I am going to check then (and also the logs.. )
thanks

**Comment by pventafridda** [comment]
After quick check for me it does not work

**Comment by SergioDaSilva82** [comment]
just give a try about the way I did and check if your issue is fixed.

**Comment by SergioDaSilva82** [comment]
can you send a screen shot about how it looks in your?

I had to make a clean install.

**Comment by pventafridda** [comment]
it is the scrollbar bitmaps generally not painted on PC, on any page. 
.

**Comment by brunotl** [comment]
You have wrong bitmap

Le 22 mars 2015 à 18:37, Paolo Ventafridda <notifications@github.com> a
écrit :

it is the scrollbar bitmaps generally not painted on PC, on any page.
.

—
Reply to this email directly or view it on GitHub
<https://github.com/LK8000/LK8000/issues/619#issuecomment-84663360>.

**Comment by SergioDaSilva82** [comment]
Bruno,

remember I had the same issue? I think I overwrite the new _Bitmaps folder
with the one from 5.0A release

**Comment by brunotl** [comment]
Bitmap has changed if you use bitmap from 5.0 you have problem for sûre

Le 22 mars 2015 à 18:40, SergioDaSilva82 <notifications@github.com> a
écrit :

Bruno,

remember I had the same issue? I think I overwrite the new _Bitmaps folder
with the one from 5.0A release

On Sun, Mar 22, 2015 at 1:39 PM, Bruno de Lacheisserie <
notifications@github.com> wrote:

> You have wrong bitmap
>
> Le 22 mars 2015 à 18:37, Paolo Ventafridda <notifications@github.com> a
> écrit :
>
> it is the scrollbar bitmaps generally not painted on PC, on any page.
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LK8000/LK8000/issues/619#issuecomment-84663360>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LK8000/LK8000/issues/619#issuecomment-84663480>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/LK8000/LK8000/issues/619#issuecomment-84663674>.

**Comment by pventafridda** [comment]
How can I have wrong bitmaps on PC? They are still the old SCROLLBARTOP etc. BMP .
Nothing changed.

**Comment by pventafridda** [comment]
why did they change, we are still using GDI on Windows..
they were 32x32 4 bit in that case.
Now they are 64x32 8 bit .

**Comment by SergioDaSilva82** [comment]
Paolo, try to use theses, were changed 5 months ago:

https://github.com/brunotl/LK8000/blob/master/Common/Distribution/LK8000/_System/_Bitmaps/SCROLLBARTOP.BMP

https://raw.githubusercontent.com/brunotl/LK8000/master/Common/Distribution/LK8000/_System/_Bitmaps/SCROLLBARBOT.BMP


https://github.com/brunotl/LK8000/blob/master/Common/Distribution/LK8000/_System/_Bitmaps/SCROLLBARMID.BMP

On Sun, Mar 22, 2015 at 1:48 PM, Paolo Ventafridda <notifications@github.com
> wrote:

> why did they change, we are still using GDI on Windows..
> they were 32x32 4 bit in that case.
> Now they are 64x32 8 bit .
>
>
> From: Bruno de Lacheisserie
> Sent: Sunday, March 22, 2015 6:43 PM
> To: LK8000/LK8000
> Cc: Paolo Ventafridda
> Subject: Re: [LK8000] Logbook: bitmaps error (#619)
>
> Bitmap has changed if you use bitmap from 5.0 you have problem for sûre
>
> Le 22 mars 2015 à 18:40, SergioDaSilva82 <notifications@github.com> a
> écrit :
>
> Bruno,
>
> remember I had the same issue? I think I overwrite the new _Bitmaps folder
> with the one from 5.0A release
>
> On Sun, Mar 22, 2015 at 1:39 PM, Bruno de Lacheisserie <

**Comment by brunotl** [comment]
5.0 bitmap are wrong ! But if you prefer to don't trust me it's your choice

Le 22 mars 2015 à 18:43, Paolo Ventafridda <notifications@github.com> a
écrit :

How can I have wrong bitmaps on PC? They are still the old SCROLLBARTOP
etc. BMP .
Nothing changed.

**Comment by pventafridda** [comment]
Oh now I see why..
