### ISSUE TITLE
Help windows not getting scroll bar

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#622]
On both PC and linux, for example system config menu 15 Alarms  Gear Warning.
Text is line wrapped correctly, but the scroll bar is missing and the help is truncated

**Comment by SergioDaSilva82** [comment]
Same issue of this report?
https://github.com/LK8000/LK8000/issues/619

**Comment by pventafridda** [comment]
no, this is scrollbar totally missing.
