### ISSUE TITLE
MapWindow thread still getting input while on dialogs

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#630]
From main map, menu config Basic settings, for example.
Click on the blue background of the settings' window, near wind load , between Wing load and QNH or in the space between efficiency and Altitude. You hear the multimap sound and map is changing in the background.
I am not sure if this may lead to critical crashes or not.

**Comment by brunotl** [comment]
not real problem, but fixed.

**Comment by pventafridda** [comment]
great thanks
i think it could instead be a critical problem in flight.
