### ISSUE TITLE
Long Press on Menu Button

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#632]
I would like to have an option inside of Display Menu that could change the option in all the map screens.

For example, long press on "Terrain OFF" would put terrain off in all the map screens.

**Comment by pventafridda** [comment]
Long-short press of the screen is always a confusing operation to people.
What we can do is create a custom key for this operation (terrain all off) and other similar.

**Comment by SergioDaSilva82** [comment]
that seems a good option too.

**Comment by parapenT1sta** [comment]
@pventafridda I don't think you need to waste your time with this. I am closing it.
