### ISSUE TITLE
Kobo: Click on UTM message box doesn't work

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#635]
Paragliding mode with no Task, long click on the compass (top right corner) give us UTM coordinate info.

Before the message box would close if we click on top of it but now it doesn't work.

**Comment by SergioDaSilva82** [comment]
Thank you for the quick fix!

**Comment by pventafridda** [comment]
Maybe you can say "Kobo" only if it does work on Linux but it does not work on kobo.

**Comment by SergioDaSilva82** [comment]
I wrote Kobo to tell where I tested it. Kobo is linux...

**Comment by brunotl** [comment]
all platform, fixed
