### ISSUE TITLE
Pictorials in waypoint details broken

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#648]
Terrain is totally random.

**Comment by brunotl** [comment]
what is the problem ?
![image](https://cloud.githubusercontent.com/assets/858626/7343104/6cfe5a18-ecbd-11e4-8191-18635e8d4ac0.png)

**Comment by pventafridda** [comment]
the ptoblem is that terrain painted is fake. not true. invented and 
sometimes not eventi painted
---
Sent from mobile



Il 27 Aprile 2015 09:12:09 Bruno de Lacheisserie <notifications@github.com> 
ha scritto:

**Comment by brunotl** [comment]
nothing is random, 
background bitmap is just painted with OR operator ( SRCPAINT in GDI) 
so bitmap color is mixed with background color.

**Comment by pventafridda** [comment]
Ok I fix it myself.

**Comment by brunotl** [comment]
already done

**Comment by brunotl** [comment]
why reopen ?

**Comment by pventafridda** [comment]
You ask why, I think you did not understand what is the problem.
I prepare some snapshots since you dont check .

**Comment by pventafridda** [comment]
ok it is broken in the last v50 too
