### ISSUE TITLE
waypoint icons not fully transparent on linux

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#649]
Check on DEMO the bridge "Paderno D ADDA", it is transparent on Windows, but white-filled on linux

**Comment by brunotl** [comment]
are you sure ?
![image](https://cloud.githubusercontent.com/assets/858626/7343137/b9e4b944-ecbd-11e4-86f4-6fccfca4eae5.png)

**Comment by pventafridda** [comment]
yes. the terrain inside the bridge icon in your picture is white, which is 
wrong. look on 5.0 there is no white
---
Sent from mobile



Il 27 Aprile 2015 09:14:10 Bruno de Lacheisserie <notifications@github.com> 
ha scritto:

**Comment by brunotl** [comment]
tranparency is defined by mask, so no bug in 5.3
![image](https://cloud.githubusercontent.com/assets/858626/7345552/fb8be238-ecd5-11e4-9fd8-c59819a6264f.png)

**Comment by pventafridda** [comment]
i made the bridge bitmap and i am saying that it is not painted correctly 
which is 100% sure. i will fix it myself

---
Sent from mobile



Il 27 Aprile 2015 12:08:18 Bruno de Lacheisserie <notifications@github.com> 
ha scritto:

**Comment by brunotl** [comment]
not related to transparency.
BMP to PNG convertion need to force output format to PNG24 otherwise, grey line are converted to white

**Comment by brunotl** [comment]
already done

**Comment by pventafridda** [comment]
![new334](https://cloud.githubusercontent.com/assets/527966/7357101/cb9cbd3e-ed2c-11e4-9652-698b64f43ec6.jpg)
this is the correct v5.0.  It is still wrong in master.

**Comment by brunotl** [comment]
look your icon, transparency is defined by mask, ( left part of bitmap file
)

if 5.0 use same bitmap, (far i know nobody have replaced) bug are in 5.0 ...

**Comment by pventafridda** [comment]
no transparency depends also on what is in the right part.
I remember I had to deal with both . 
5.0 is displaying correctly, and not by random chance.

**Comment by brunotl** [comment]
if transparency is defined by white color in right part, why we have mask ? 

so, we have to option : 
 - use only mask for transparency and update bridge bitmap in this way 
 - remove all mask from all bitmap and use white for transparency

second method have advantage of less cpu usage, no need to copy mask & image ...

**Comment by pventafridda** [comment]
The bitmap is wrong. wait

**Comment by pventafridda** [comment]
The bitmap you show is not correct.
In v50 we have another.
![new337](https://cloud.githubusercontent.com/assets/527966/7357547/c460396c-ed2f-11e4-91bc-f5b572b7852d.jpg)

**Comment by brunotl** [comment]
where is this bitmap ? 

this is change log of this bitmap ( hight and low res ): 

https://github.com/LK8000/LK8000/commits/master/Common/Distribution/LK8000/_System/_Bitmaps/BRIDGE.BMP
https://github.com/LK8000/LK8000/commits/master/Common/Distribution/LK8000/_System/_Bitmaps/BRIDGE_H.BMP

**Comment by pventafridda** [comment]
I am wrong that bitmap was an old one.
The current bitmap is the one you reported.

**Comment by pventafridda** [comment]
I fixed the bitmaps to paint transparently inside the bridge, as it should. New bitmap in next commit.
