### ISSUE TITLE
Not saving options?

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#658]
Paolo,
I don't if is a bug or the new way LK8000 will hand certain options but I got this report of a pilot using Kobo with all the commits up to May 4th.

only tested in the SIM mode: 

1. In the past after the start glider position on the map was over the "home waipoint" - now after restart glider position is in the middle of the map 
2. I am using only the "variobar" on the main screen - now after each restart I have to swich two times overlays to do not display overlays and display only the variobar 
3. FAI traingle display have to be activated everytime after restart of the LK8000

**Comment by pventafridda** [comment]
New way see commits
---
Sent from mobile



Il 05 Maggio 2015 22:32:08 SergioDaSilva82 <notifications@github.com> ha 
scritto:

**Comment by SergioDaSilva82** [comment]
I missed that commit! thank you so much ;)

**Comment by pventafridda** [comment]
You are much welcome!
I wonder if you could make the “CHANGES” somewhere updated..
Truly we should do it ourselves but we have to catch up with all the changes so far now, and it is quite long work..
I prefer to work on the UI.

**Comment by SergioDaSilva82** [comment]
I can try to do that, I usually keep eye on the new features but I really
missed that I don't know how.

I will see if I have sometime on the weekend.

**Comment by pventafridda** [comment]
yesss please go backward in commit history, you can use the wiki section on github , it is then easy to take the changes and put them in a text file when we do a release..
And we could all partecipate to prepare the docs in this way!

**Comment by SergioDaSilva82** [comment]
Something like this? https://github.com/LK8000/LK8000/wiki/LK8000-Changelog

**Comment by pventafridda** [comment]
Yes exactly. Maybe with decent font size!!!! It is forbidden on the wikis to use over 40ppt fonts!! haha

**Comment by SergioDaSilva82** [comment]
where can I change the font size?

**Comment by pventafridda** [comment]
i was joking
