### ISSUE TITLE
Glitch: Ext. Sounds option in landscape mode

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#661]
In Kobo, in Device Setup using landscape mode the Ext. Sound box is almost hidden.

**Comment by jaaaaf** [comment]
I will get this one!

2015-05-06 22:36 GMT+02:00 SergioDaSilva82 <notifications@github.com>:

> In Kobo, in Device Setup using landscape mode the Ext. Sound box is almost
> hidden.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LK8000/LK8000/issues/661>.
>



-- 
Jack.

**Comment by jaaaaf** [comment]
I make a pull request (#663) to fix this, but maybe there is a better
solution to do it.
I'm not a specialist of git, so tell me.

2015-05-07 18:22 GMT+02:00 Jacques Fournier <jaaaaf@gmail.com>:

> I will get this one!
>
> 2015-05-06 22:36 GMT+02:00 SergioDaSilva82 <notifications@github.com>:
>
>> In Kobo, in Device Setup using landscape mode the Ext. Sound box is
>> almost hidden.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/LK8000/LK8000/issues/661>.
>>
>
>
>
> --
> Jack.
>



-- 
Jack.
