### ISSUE TITLE
FAI Paralog interface

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#670]
on linux use a named pipe

**Comment by SergioDaSilva82** [comment]
Good news Paolo! I hope you can make this happen.

**Comment by pabloaugusto** [comment]
XCSoar already had valid logs, maybe a watch on his code can accelerate things and make it's happen and making possible change from xcsoar to lk8000 (my case).

**Comment by pventafridda** [comment]
XCSoar is accepted because they did not make a plugin for the UK people like we did.
They did well. I would do bad to spend more time on paraglider's logging.
We do have one working for OLC, and it worked for years.
