### ISSUE TITLE
Kobo & Digifly

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#672]
Hi, 
Thank you for project LK8000 on Kobo development. I am testing LK8000 with vario transmiting data in Digifly Leonardo protocol. There is a problem. LK8000 does not show HBAR. Pressure indications from vario get to LK8000. It is visible in added NMEA log. GPS and vario works well. IN LK8000 program as a device is choosen Digifly. With the same hardware XCsoar works well and HBAR shows properly. I add Digifly Leonardo protocol's specification, which I found. Please fix this mistake. Thank you ever so much. 

Sincerly, 

Vytautas 

https://www.dropbox.com/s/27r32nny9ooi04d/digifly.zip?dl=0

**Comment by pventafridda** [comment]
this is NOT the place for support to end user.
The forum is the place.

**Comment by SergioDaSilva82** [comment]
He was reporting a bug. I will post in the forum. Sorry

**Comment by pventafridda** [comment]
I am not going to check if the user has disabled baro altitude.
