### ISSUE TITLE
Redesign MM bitmaps

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#678]
40x40  squared, not circled

**Comment by SergioDaSilva82** [comment]
Now that you are working on this I would recommend to use letters instead of numbers. Sometimes I forget what is the meaning of each number
M = Alternative map
T = Target
A = Airspace
V = VisualGlide

**Comment by pventafridda** [comment]
uh, well..  I dont think  we have to change numbers with letters for multimaps. 
People got used to numbers that represent the sequence .
The most important change will be the MM0 (the main map) and the icons around cruise final glider that are plain misunderstood right now.
We have to test, and adjust. But first I need to make the code that calculates the positions based on icon sizes, then we change the icons.
did you test the page 12 fonts?

**Comment by SergioDaSilva82** [comment]
yes,  I did! I like the fact we get about 4 fields on the bottom bar when
using the max.  size. Well done.

I just need to test it a little bit more

**Comment by SergioDaSilva82** [comment]
Do you think is possible to add the same options for the bottom bar to the Map overlay text? I think will be better than big and normal

**Comment by pventafridda** [comment]
it takes time, currently I had a few months ago fixed the overlays to a decent auto-resolution point.
I must check to see how big work it is.
