### ISSUE TITLE
Configurable overlays in page 12

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#680]
The new rescaling engine is half of the work done. New overlays will be rescalable as well, maybe with the exception for time gates for paragliders (lots of informations tightly tuned to fit in little space, no reason to make it better).
We shall have thus dedicated fonts for overlays and abandon the big-small.
If the work proves to be beyond a reasonable time I will suspend it, no warranty.

**Comment by pventafridda** [comment]
good news, it comes out quite nicely. we are abandoning big font-small font for overlays, and have an 11 levels choice. Really worth while!

**Comment by SergioDaSilva82** [comment]
Well done! I was waiting for this for a while.

**Comment by pventafridda** [comment]
I need some more time to fix it.. quite long work.
