### ISSUE TITLE
Snail Trail width doesn't change with 1.5Km zoom

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#697]
Using PG mode on 1.5Km zoom in cruise, doesn't matter how wide we set up the snail trail, is always the same. Even when is set to 50. 

The issue is also in thermal mode.

**Comment by pventafridda** [comment]
on v5 is it working?

**Comment by SergioDaSilva82** [comment]
Yes, it is working.

I forgot to tell, this issue report was about Kobo version.

**Comment by pventafridda** [comment]
It does change. It does not change (on any zoom level) when the netto vario is 0, which seldom happens in real flight. Anyway I have fixed it.
