### ISSUE TITLE
Notepad not reading notepad.txt as in v5. PC VERSION

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#698]
The text is not printed, or printed only the first line.
Incompatible with existing notepad files made by users.
PC PNA versions

**Comment by brunotl** [comment]
same bug already fixed for dlgWaypointDetails & dlgHelp

https://github.com/LK8000/LK8000/commit/cf2198cf49e24fb4e5424984808af85e3a365068
https://github.com/LK8000/LK8000/commit/a3bc4136614194995e62df825f27d800c073b216
