### ISSUE TITLE
PNA version not usable

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#700]
CPU very high percentages, very slow response timing, touch response terrible.
Sometimes we get double touch detection since the other one is handled so late.

It seems that we have only a small 2% overhead for new libraries, except for terrain drawing.
Old version   New version  
17%                 19%             only bottom bar, no topo no terrain no overlays
20%                  23%            overlays only, no topo no terrain
22%                  24%            with topo
35%-40%          65%            with terrain

Need more checking

**Comment by brunotl** [comment]
fixed !

**Comment by pventafridda** [comment]
online, patching!

**Comment by pventafridda** [comment]
PNA VERSION VERY USABLE!
