### ISSUE TITLE
Fix disposition of menu buttons on portrait mode

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#707]
They are not spaced and positioned properly expecially  vertically.
Button n13 is overlapping button 1.

**Comment by SergioDaSilva82** [comment]
I think this one can be closed.

**Comment by brunotl** [comment]
fixed by commit 4802cdd75d78f047dd240f692a71bfbe1709cf9a

**Comment by SergioDaSilva82** [comment]
Paolo, I think you forgot to close this issue.
