### ISSUE TITLE
graphics glitch in Linux-Version 5.3e0

### ISSUE THREAD

**Issue by klinkenberg** [LK8000/LK8000#725]
There is a graphics glitch within the Linux-Version 5.3e0 which was introduced into the Linux-version sometimes in spring.
The appended pictures show the map viewing differences (5.0a(PC, top) to 5.3e0(Linux, button)) in the very flat lands, especially  "flatland mountains"  appear in the Linux-version (The height differences at the coast in reality are maximum a few tens of meters).

![flatlands_lk50a](https://cloud.githubusercontent.com/assets/13381668/8748476/12d6f84c-2c9b-11e5-8a3e-31d64fded531.jpg)
![flatlands_lk53e0](https://cloud.githubusercontent.com/assets/13381668/8748487/1ffa8b60-2c9b-11e5-84e4-545e249a5d02.jpg)

**Comment by pventafridda** [comment]
thanks ernst, problem is well exposed.

**Comment by brunotl** [comment]
what is terrain & topology file ?

**Comment by klinkenberg** [comment]
Am Dienstag, 28. Juli 2015, 11:09:34 schrieb Bruno de Lacheisserie:
> what is terrain & topology file ?

Hallo Bruno,

give me please a more capable email-adress I can send the files to. Github is 
restricted to somewhat 4MB 

Greetings Ernst-Dieter

> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LK8000/LK8000/issues/725#issuecomment-125513281


-- 
Dr. E.-D. Klinkenberg
Siegfried-Witte-Str. 3
D-18055 Rostock
email d.klinkenberg@gmx.net
Tel: 0381-120 39 38
Mobil: 0162-90 31 368

**Comment by pventafridda** [comment]
awaiting for ernst to confirm it is fixed

**Comment by klinkenberg** [comment]
I confirm, Bug is fixed
