### ISSUE TITLE
PNA only: multiselect not working in multimaps

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#729]
reported by ulli

**Comment by brunotl** [comment]
tested on all multimap, all work on PNA ...

**Comment by pventafridda** [comment]
Oh interesting.  I tested on V1 which is CE 6. Ulli has the same. It does 
not work there.
I will check it works on CE5.

Maybe it is the same problem of poco gettick.
---
Sent from mobile



Il 30 Luglio 2015 10:45:54 Bruno de Lacheisserie <notifications@github.com> 
ha scritto:

**Comment by brunotl** [comment]
tested on WM6.5

**Comment by pventafridda** [comment]
That is CE 5
---
Sent from mobile



Il 30 Luglio 2015 11:28:45 Bruno de Lacheisserie <notifications@github.com> 
ha scritto:

**Comment by pventafridda** [comment]
I tested on V2, it works (CE 5). I tested on V1, CE 6 does not work. It must be the poco library. no problem

**Comment by pventafridda** [comment]
It is the LKEVENT_LONGCLICK  not correct in CE 6.

**Comment by brunotl** [comment]
work fine on  CE 6.00 (build 2217)

**Comment by pventafridda** [comment]
On emulator ?
---
Sent from mobile



Il 04 Agosto 2015 16:13:43 Bruno de Lacheisserie <notifications@github.com> 
ha scritto:

**Comment by brunotl** [comment]
No Bug.
with correct "_System\DEFAULT_MENU.TXT" file, all work fine on V1.

**Comment by pventafridda** [comment]
I confirm.
