### ISSUE TITLE
Dialog not working correctly

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#734]
dlgAirspaceDetails xml has not changed since v5, but the rendering is now different.

Previously:
![new340](https://cloud.githubusercontent.com/assets/527966/9152869/32000914-3e3b-11e5-8943-71cecf748514.jpg)

Now:
![new341](https://cloud.githubusercontent.com/assets/527966/9152870/394d602c-3e3b-11e5-8846-0a45329a4778.jpg)

Furthermore, we are now painting the background map that is not updated (clock is stopped).

**Comment by pventafridda** [comment]
The color of unselectable buttons (like Top Base Range etc.etc.) should be darker to mean "disabled".

**Comment by AlphaLima** [comment]
Works for Linux now, but still not for windows.
Tested with an complete updated installation.


Am 11.08.2015 um 00:03 schrieb Paolo Ventafridda:

**Comment by pventafridda** [comment]
I confirm it was fixed, the rendering was correct.
The button not working were another issue.
