### ISSUE TITLE
sideview / visual glide : font size is wrong on hight definition screen

### ISSUE THREAD

**Issue by brunotl** [LK8000/LK8000#738]
checked on kobo GLOHD, screen resolution : 1072x1448

**Comment by brunotl** [comment]
worst case : 1999 x 1142
![image](https://cloud.githubusercontent.com/assets/858626/9239133/2e3778d2-4159-11e5-94d7-6d8d144d577d.png)

**Comment by pventafridda** [comment]
ok my job
