### ISSUE TITLE
Boxed drawing offsetted

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#781]
Some drawings seem to be lightly offsetted while boxing. 
![pic](https://cloud.githubusercontent.com/assets/527966/12312495/41ff670a-ba60-11e5-943a-7e7bcf3fc528.jpg)
![p2](https://cloud.githubusercontent.com/assets/527966/12312496/43b26cc8-ba60-11e5-91db-cbd70082b874.jpg)

Looks like the inner box is not aligned on top correctly, by 1 pixel.

**Comment by brunotl** [comment]
![image](https://cloud.githubusercontent.com/assets/858626/12313167/6a15db52-ba65-11e5-8da3-595b47821f08.png)
![image](https://cloud.githubusercontent.com/assets/858626/12313102/fc8d2bd0-ba64-11e5-81ed-3b4ab832b878.png)

no problem on real hardware
seem's depends of OpenGL Driver implementation...

**Comment by pventafridda** [comment]
ok thx I check
