### ISSUE TITLE
LT Server port crash 

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#799]
On PC (at least..) clicking on Port configuration of LT server in Pilot setup is crashing LK

**Comment by SergioDaSilva82** [comment]
Paolo,

Are you sure about it? I compiled a version with commits until Jan 30, and if I run a new installation, it doesn't crash in FLY and SIM mode.

http://tinyurl.com/lk8000v6alpha

**Comment by pventafridda** [comment]
yes I am sure, it happened last night. it doesnt happen now, so it is not an easy problem

**Comment by pventafridda** [comment]
it just happened again by clicking on help , in the LT screen

**Comment by SergioDaSilva82** [comment]
I can confirm, hitting the Port and then Help it crashes.

**Comment by brunotl** [comment]
easy with debugger : found in 5 second ....

another global variable uninitialized...

**Comment by pventafridda** [comment]
Looks like HELP button is in the XML but not managed by the code.
