### ISSUE TITLE
Crash using Custom Menu (tested on PC)

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#803]
By davesalmon

> Found a minor problem, so far only seems to be on PC version, PNA works OK. 
> I wanted to run through the different terrain colours, so configured Custom Menu so that 3 was Colour terrain +, and 4 was Colour terrain -. As soon as + button is pressed a Windows message comes up saying the program has stopped working, and it shuts down.

http://www.postfrontal.com/forum/topic.asp?TOPIC_ID=8110

**Comment by pventafridda** [comment]
fixing
