### ISSUE TITLE
Duplicates in airspace multiselection list

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#807]
Reported by Ernst: airspace list is showing a duplicated (verified).
And we have twice Disabled in the custom key lists. Maybe unrelated.
Investigating..

**Comment by brunotl** [comment]
for Custom Key lists, still we use array index instead of id, we can't remove second.

second "disable" replace removed "Active Map On/Off"

**Comment by pventafridda** [comment]
ah good. you are right!
If we change array index, then we must change configuration name, and people must reconfigure .. no reason.

So problems are unrelated.

**Comment by pventafridda** [comment]
I think it is a problem in the airspace sorting while looking for underneath airspace.
Matching is not correct, maybe. Anyway it is an airspace issue.

**Comment by pventafridda** [comment]
So far I cannot confirm anymore the problem. The only duplicate I got was real .
Same for Ulli. I am declassing the issue.

**Comment by AlphaLima** [comment]
Ernst also confirmed using two airspace files with partly identical 
airspace definitions.


Am 10.02.2016 um 01:43 schrieb Paolo Ventafridda:
