### ISSUE TITLE
Airspace, negative distance shown in multiselection list

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#808]
Strange. Asking for a multiselection list on the map, I also get some airspaces.
Sometime I get a negative distance value for one of these. 
Selecting the item, the distance is correctly positive.

I noticed this item appears twice in the list, sometimes.

**Comment by AlphaLima** [comment]
As far as I remember neg. values mean you are "inside" the airspace.
But inside is separate for vertical and horizontal. So it can mean 
under/above left/right of it.
Only if vert. *and* horiz. are negative you're "inside" the particular 
airspace.

For the multiselect we only show the horizontal distance so neg values 
mean you're under, above or inside the airspace.
IT is a precious info but maybe not documented correctly.



Am 09.02.2016 um 18:05 schrieb Paolo Ventafridda:

**Comment by AlphaLima** [comment]
Maybe it is a better solution to show the abs value and have an indicator
(in under above) but I'm afraid it is a language problem and need much 
more space filling the line.


Am 09.02.2016 um 18:05 schrieb Paolo Ventafridda:

**Comment by pventafridda** [comment]
OK. Can you please check then the duplicates issue? I could verify it happens.
Only for airspaces .. Ernst has a german airspace eventually where it happens

**Comment by AlphaLima** [comment]
Already did it, cold not find a problem.
Probably the airspace is defined twice.


Am 09.02.2016 um 19:37 schrieb Paolo Ventafridda:

**Comment by AlphaLima** [comment]
Can you send me your airspace file and the particular AS where it happened?


Am 09.02.2016 um 19:37 schrieb Paolo Ventafridda:

**Comment by AlphaLima** [comment]
I had quite often multiple defined airspaces.
Not easy to see but simple to prove. Disable the Airspace if it remains 
it is multiple defined.
If you select the same airspace file for Airspace1 and Airspace2 you can 
emulate the effect for every airspace.


Am 09.02.2016 um 20:11 schrieb Ulrich Heynen:

**Comment by pventafridda** [comment]
I confirm you are right concerning my example!
Checking Ernst now

**Comment by pventafridda** [comment]
unfortunately ernst did not open an issue on github for this, so i am sending to you via email details

**Comment by pventafridda** [comment]
OK it looks intentional, so I am declassing to change request. Not that I want or need to change it, personally. negative stands for out of airspace distance. I would close it.. you tell me.

**Comment by AlphaLima** [comment]
It is like this since the very first Multiselect. No complains so far.
I suggest to leave it as it is and add a sentence in the docs.

Am 10.02.2016 um 01:45 schrieb Paolo Ventafridda:
