### ISSUE TITLE
borderline crash

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#827]
DrawTerrain.cpp 
trenderer exists but terrain_ready is false because TerrainRenderer was aborted while checking for rc.right and rc.bottom compliancy (line 111, around).
We then call CloseTerrainRenderer and we have a crash while doing
delete trenderer

**Comment by brunotl** [comment]
how do you have rc.right or rc.bottom less than 1 ?

**Comment by pventafridda** [comment]
I dont remember how. Maybe when we resize and there is a bug somewhere else.
In such case, we shall never know. The check and assertion was made to let us know , precisely.

**Comment by brunotl** [comment]
segfault happen because few pointer are not initialized, nothing more...
