### ISSUE TITLE
LKDrawBottomBar clipping 

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#830]
BufferTitle is not clipped.
The name of BestAlternate infoboxes (distance, req.eff etc.etc.) is printed as title in the bottom bar, but it is no more clipped to max some characters. Result is overlapping.
![pic](https://cloud.githubusercontent.com/assets/527966/13410525/961bcda4-df38-11e5-885c-09e397b12eb0.jpg)

**Comment by pventafridda** [comment]
In other words, I think CropString is gone having a beer, or two.. but not working today.

**Comment by brunotl** [comment]
fixed
