### ISSUE TITLE
Dialog multiselection on close

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#838]
There is a possible problem with multiselection dialog. It is visible on PNA being slower than a PC. Long click on map for a multiselection, the list of items appears in dialog.
No selection, simple close. For a short while, the dialog is printed again with all items being the same: the first one in original list, and all them are selected in yellow.
Despite many attempts on PNA I cannot say it is creating any problem, so it is more likely a glitch.

**Comment by brunotl** [comment]
Fixed

**Comment by pventafridda** [comment]
yes I was closing it in fact thanks!
