### ISSUE TITLE
Panning with OpenGL slow

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#841]
It is related to the way we refresh using OpenGL, so this is only a reminder.
Of course panning is faster when using Windows, because we refresh only once every some time.

**Comment by brunotl** [comment]
Interesting, how much time is spend in UpToDate() ?

**Comment by pventafridda** [comment]
I don't know. It is called even 150 times in less than a second. But slow 
pan is not due to this. As you said we don't wait like on windows and we do 
refresh every move so it is normal to be slow.
Probably on fast cpu no problems and I close the issue.

---
Sent from mobile



Il 08 Marzo 2016 21:48:49 Bruno de Lacheisserie <notifications@github.com> 
ha scritto:

**Comment by brunotl** [comment]
150fps ? We can't says that slow ...

**Comment by pventafridda** [comment]
All I can say is that on PC Linux at 2ghz it is slower than on a 500mhz pna
---
Sent from mobile



Il 08 Marzo 2016 22:33:22 Bruno de Lacheisserie <notifications@github.com> 
ha scritto:

**Comment by brunotl** [comment]
drag&move in pan mode profiling on LINUX i686 virtual machine

MapWindow::Render() call graph  (% of time & call count)

![image](https://cloud.githubusercontent.com/assets/858626/13637983/6dfc3d4e-e60a-11e5-8460-bd223ee4da55.png)

concerning UpToDate overhead :
   UpToDate() per call cycle estimation : 2 702
   DrawTerrain() per call cycle estimation : 3 663 376

so overhead is 0.073%

**Comment by pventafridda** [comment]
Ok overhead of UpToDate is zero, I already acknowledged that.
I dont understand if you confirm the slow pan with OpenGL, although for a totally different reason.
