### ISSUE TITLE
Kobo changing orientation on startup 

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#842]
It seems that after configuring an external device for gps feed, the rotation on Kobo (at least) is changed. 
I check.

**Comment by pventafridda** [comment]
I dont remember if this is fixed, I confess.

**Comment by SergioDaSilva82** [comment]
Maybe is related to this fix? https://github.com/LK8000/LK8000/commit/d2a99a070960f96e9f18f5c308afe8efc6373357

@brunotl ?

**Comment by brunotl** [comment]
i think yes.

**Comment by parapenT1sta** [comment]
@pventafridda I think you can close this ticket.
