### ISSUE TITLE
PPC2003 CPU infobox always 0%

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#846]
Not checked on PPC2002.

**Comment by brunotl** [comment]
GetIdleTime() don't work on PPC2003, in V5 CPU are draw time in fact. so it's wrong.

only one way for fix that : no CPU infox on PPC2003...

**Comment by pventafridda** [comment]
I do not agree that it is wrong. How to get CPU usage on CE?
1) call GetCPUIdleTime() and perform your calculations (this is good for
system-wide CPU usage)
2) call GetThreadTimes() and perform your own calculations (good for a
single thread's CPU usage, or an entire process if you call it once for each
thread in the process)
Anyway, dead platform, no reason to spend time on it.

**Comment by pventafridda** [comment]
i fix CpuSummary, just because it is 1 minute work
