### ISSUE TITLE
STF speed to fly broken

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#855]
The STF is reporting crazy values for gliders.
Update: not so crazy but strange. v5 STF 100kmh, v6 STF 88kmh. Same situation.

**Comment by pventafridda** [comment]
The commit b2846c5975df712ca976615e27621814d1de5c83  is changing the STF method. 
For gliders, and I believe also for PGs, the STF is often wrong,  showing a STF of minsink everytime.
Fast solution is revert the commit .

**Comment by brunotl** [comment]
Polar DG 300 : 

MC 0    ->   99 km/h
MC 0.5 -> 110 km/h
MC 1    -> 121 km/h
MC 1.5 -> 131 km/h
MC 2    -> 140 km/h
MC 3    -> 156 km/h

nothing wrong.

**Comment by pventafridda** [comment]
Comparing v5 on a glide, i read STF on v5 and 83-89 in v6.  Speed are quite always different.
In any case, it is wrong for gliders.

**Comment by brunotl** [comment]
v5 is not valid reference. only valid way for check is polar equation and mathematic ...

**Comment by pventafridda** [comment]
Then the mathematics in v6 are wrong.
Because it is out of any question that the STF is wrong for gliders.

**Comment by pventafridda** [comment]
I am no more sure, I write to you.
