### ISSUE TITLE
Multitarget waypoint name not clipped in multimaps

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#868]
I remember not too much time ago Bruno you made a fix for main map target name clipped correctly.
Same thing is needed for multimaps..

**Comment by brunotl** [comment]
cf . "Common\Source\Draw\LKDrawLook8000.cpp" line 236 - 238 and line 471 to 475

**Comment by pventafridda** [comment]
ok thanks later i fix

**Comment by pventafridda** [comment]
No the problem is another. LKDrawLook is the same for all multimaps. The issue is around the clip region when we have a vario displayed initially.
I am fixing.

**Comment by pventafridda** [comment]
Argh, I am wrong. The ClipRect is simply cutting the text at the right point, already.
This is how it is working. But it is cutting the last letter, if existing, it is not removing it entirely. 
I thought we had fixed this in some other part of the code.

**Comment by AlphaLima** [comment]
checked with V7.x on LINUX, PC and Android. 
No more problem at all.
CAN BE CLOSED!
