### ISSUE TITLE
Buttons ScreenView Zoom in out very slow, RefreshMap not triggering 

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#871]
On both Windows and Linux we are no more getting fast response to zoom buttons.
InputEvents line 1247 is forcing RenderMap but it is not enough.
No idea.

**Comment by brunotl** [comment]
define "fast response" please.

**Comment by pventafridda** [comment]
Click on the moving map for zoom. Response is fast.
Click on the zoom in – zoom out buttons, response is delayed.
On PC: it is faster but quick button presses are ignored (I have to check for debouncing maybe).
On OpenGL: very slow response.
Which is strange, since on moving map action is immediate.
