### ISSUE TITLE
Overlay_RightBottom shows AUX2 instead of AUX3 (5.3o)

### ISSUE THREAD

**Issue by robix** [LK8000/LK8000#876]
After setting up new custom overlays in 6.0 beta (5.3o) RightBottom shows same data as RightMid.

Ran through the code, maybe this is the cause?

```
if (Overlay_RightBottom==OAUX)
                LKFormatValue(GetInfoboxType(2), true, BufferValue, BufferUnit, BufferTitle);
```

I guess it should be GetInfoboxType(3)

**Comment by pventafridda** [comment]
You are correct, but specifically ONLY for paragliders.
Checking on gliders mode, I found no problem. I fix it many thanks robix!
Or do you want to fix it and commit it?

**Comment by robix** [comment]
Thanks Paolo. Yes, this is in paragliding mode. I'm not into programming too much so it'd be great if you can fix it! Thanks again.

**Comment by pventafridda** [comment]
thanks done!
