### ISSUE TITLE
23 Para/Hang Gliders Specials (PNA)

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#883]
I only can get 23 Para/Hang Gliders Specials menu on my PNA (Holux 61CS) when I set Engineering Menu: ON.

Clean install of 5.0A then updated to 5.3P version.

PNA model: Holux 61CS (in vertical position).

**Comment by pventafridda** [comment]
i fix it thx

From: Sérgio Da Silva 
Sent: Monday, April 25, 2016 10:52 AM
To: LK8000/LK8000 
Subject: [LK8000/LK8000] 23 Para/Hang Gliders Specials (PNA) (#883)

I only can get 23 Para/Hang Gliders Specials menu on my PNA (Holux 61CS) when I set Engineering Menu: ON.

Clean install of 5.0A then updated to 5.3P version.

PNA model: Holux 61CS (in vertical position).

**Comment by SergioDaSilva82** [comment]
+#define NUMOFCONFIGPAGES 23? 

Instead of NUMOFCONFIGPAGES 22?
