### ISSUE TITLE
Reset comms - Version 5.3q

### ISSUE THREAD

**Issue by PhilColbert** [LK8000/LK8000#885]
Maybe a small issue with Restart comms on the kobo ( only had chance to test on there ) both devices (A&B) used to come back working in a second or so, now it waits about a minute with no data coming in on either device and then a ( automatic ) restart comms message comes up and it works once more, probably a watch dog kicking in ?

Device A - tested with bluefly and generic

Device B - TCP server.

https://goo.gl/photos/6JzPgfshffc1TauF6

**Comment by pventafridda** [comment]
Big issue probably. Unlucky version for kobo..
---
Sent from mobile



Il 30 Aprile 2016 11:30:57 PhilColbert <notifications@github.com> ha scritto:

**Comment by PhilColbert** [comment]
Not a massive issue, it does come back  in a bit of time :) not a major problem to be honest , just reporting it

**Comment by ienders13** [comment]
yes same here, manual reset kills bluefly data stream until auto re-start fixes it. I'm guessing the manual reset is not accessing the same code as the auto reset, maybe not updated since your amendments.

**Comment by pventafridda** [comment]
no it is ther rtscts management that is wrong, I have to regress that fix.

**Comment by pventafridda** [comment]
I have released a fix version for kobo on the forum
---
Sent from mobile



Il 30 Aprile 2016 13:39:31 ienders13 <notifications@github.com> ha scritto:

**Comment by PhilColbert** [comment]
Thanks, just confirming the reset comms now works as before and bluefly sounds are back, thank you !
