### ISSUE TITLE
version Q not sending sounds to Bluefly any more

### ISSUE THREAD

**Issue by ienders13** [LK8000/LK8000#886]
Hi, have had bluefly working to date with sounds set up in sound_table working fine. Now no NMEA sent to bluefly for sound. Very important feature!

Thanks,

**Comment by SergioDaSilva82** [comment]
Quick fix :)

https://github.com/LK8000/LK8000/commit/25605ba0c783efe4d4f274272b6d49ab30d1a1d3

**Comment by ienders13** [comment]
Thanks!
