### ISSUE TITLE
5.3S Trail width too thin on Kobo Glo

### ISSUE THREAD

**Issue by ienders13** [LK8000/LK8000#892]
The recent versions have reduced the snail trail to such a thin line it's barely visible.

Trail width setting has no effect.

Many thanks,

Mike.

**Comment by pventafridda** [comment]
Hello Mike, I cant find any difference in drawing the trail since months, almost an year . When did you notice this problem to appear? Which recent version?

**Comment by ienders13** [comment]
Well weirdly, I set it to 50 (Max) today, had to restart kobo for something else and now trail is fine. Pls close this. Sorry.

**Comment by pventafridda** [comment]
There was indeed a problem now fixed, and many similars. I dont have a GloHd to test on, so I am only guessing.
