### ISSUE TITLE
Button letter size too small after load profile

### ISSUE THREAD

**Issue by SergioDaSilva82** [LK8000/LK8000#900]
Tested on PC (only, have no Kobo or PDA to test at the moment)

Installed fresh 5.0A installation and upgraded to 5.3U
- Run LK8000 on simulate mode, and everything looks fine.
- Run LK8000 again but now go to Profile - System - and load any profile and then run in Simulate mode (for example)
The menu buttons will look like this:
![capture2](https://cloud.githubusercontent.com/assets/608650/15874858/40a97248-2cd3-11e6-859d-47a6ee68f2ab.PNG)

**Comment by pventafridda** [comment]
Yes I have replicated it I will fix it thx
---
Sent from mobile



Il 07 Giugno 2016 23:14:32 Sérgio Da Silva <notifications@github.com> ha 
scritto:
