### ISSUE TITLE
Flight color trace to be rescaled for hires

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#963]
Too thin on hi res,

**Comment by pventafridda** [comment]
Seems good..

**Comment by pventafridda** [comment]
Please check, it is important that the trace is big enough,,

**Comment by brunotl** [comment]
now to big, but can be change in system config, maybe only default value are wrong
kobo  eed to be check because line width is not scaled.

![image](https://cloud.githubusercontent.com/assets/858626/22477004/c2841e90-e7e4-11e6-8c8f-b6303193d17b.png)

**Comment by pventafridda** [comment]
Maybe the latest changes on ScreenScale made them big.
When do you merge them?
How is the runway working now?

**Comment by brunotl** [comment]
look good on all platform if configured to 11 instead of 16 ...

**Comment by pventafridda** [comment]
What change 11 to 16? Where?

**Comment by ToninoTarsi** [comment]
Just a curiosity : What was 16 for ? 16 pixel ? 16 mm ?
If it was only a calibrated value now the new one could be (16/16)*11 :-)  ... maybe.

**Comment by brunotl** [comment]
pixel because before commit 9b8a4f3a939303e92a86dd183407462889a87b30 snailtrail does not take account screen scaling ...

**Comment by pventafridda** [comment]
I will fix it as soon as I set up my android compile by the weekend.
Meanwhile it is worthless to change dimensions and sizes until the new scaling system is settled.

**Comment by brunotl** [comment]
sceenshot is windows ...

**Comment by pventafridda** [comment]
I know. today I work on it. I have discovered the problem. screenscale is wrong obviously cannot be used for rescaling without loss of accuracy.
Solution is to use IBLSCALE.
Rescale pixel is also wrong. because we should rescale only in reference to a 5 inches screen,  after IBLSCALE. this is the point .

**Comment by brunotl** [comment]
this why i have fixed all ScreenScale usage ...

**Comment by pventafridda** [comment]
I agree screenscale must not be used like that . when I am back home I 
write a more detailed explanation of what I have thought.


In data 2 Febbraio 2017 16:48:11 Bruno de Lacheisserie 
<notifications@github.com> ha scritto:

**Comment by pventafridda** [comment]
I take it for fixing

**Comment by pventafridda** [comment]
The problem is in the IBLSCALE . I suspect old NIBLSCALE was rounding the integer to the nearest border.
So 3.7 becomes 4.  In current scaling, we round to the lowest border. 
for niblscale 1, on dpi 330..   IBLSCALE(1)=3 *16 = 48   should be 4*16=64 .
Huge difference.

Not good to fix LKObjects.
