### ISSUE TITLE
PC version, problem with topology font size

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#965]
Not working..

**Comment by brunotl** [comment]
?

**Comment by pventafridda** [comment]
I am checking the latest master on PC. I am not drunk, I havent smoked anything special, and Topology font is wrong.

**Comment by pventafridda** [comment]
![lk438](https://cloud.githubusercontent.com/assets/527966/22045504/efcf958e-dd1a-11e6-9adc-a78a220c4b74.jpg)

**Comment by pventafridda** [comment]
It's like the font has been made for another resolution . If you rescale in page 12, it does not work too correctly. Font topology -8 should be very very small, instead it is:
![lk439](https://cloud.githubusercontent.com/assets/527966/22045562/419451ac-dd1b-11e6-96cc-c7cfc50db085.jpg)

and notice that text is overlapping.

**Comment by pventafridda** [comment]
I think the font is not used, for some reason. It worked in 6.0b for sure. Current master on PC is not using the correct font for topology, apparently.

**Comment by pventafridda** [comment]
Probably this is the only possible explanation https://github.com/LK8000/LK8000/commit/3606a44be18c8c6c99fb34e94baf3ea4ef8fcd7a

**Comment by AlphaLima** [comment]
I  worked with Fonts in FAI sectors. Will Check tomorrow

**Comment by brunotl** [comment]
fixed

**Comment by pventafridda** [comment]
Many thanks!
