### ISSUE TITLE
Rescale topology lines for hires

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#967]
Some fixes are needed here.

**Comment by pventafridda** [comment]
They seem ok to me, on 440 dpi. 
Can we close it?

**Comment by brunotl** [comment]
look very fat ...
![image](https://cloud.githubusercontent.com/assets/858626/22254292/6fba6b5a-e254-11e6-9b7d-54c38b9af1e6.png)

**Comment by ToninoTarsi** [comment]
Yes .. also too fat on my 530dpi .. As a personal preference last version was better.

**Comment by pventafridda** [comment]
Checked now against old v6 480x272, exactly the same. This is how we had topology painted for many years..

**Comment by pventafridda** [comment]
but we can change of course!

**Comment by pventafridda** [comment]
It was changed in a commit
