### ISSUE TITLE
WAYNOTES.txt on android

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#970]
Not appearing after install.

**Comment by ToninoTarsi** [comment]
Just to be sure I have understood the problem try : 
1) Delete or rename LK8000 folder on external storage
2) Restart LK8000
3) Have a look at the new created LK8000/_Waypoint folder and menu 1.
Let me know where exactly is the problem Paolo as I do not use WAYNOTES and may be I did not understand well the mechanism

**Comment by pventafridda** [comment]
I confirm that with new install the WAYNOTES is there. 
No bug, all ok. Closing . sorry
