### ISSUE TITLE
Aircraft icons still too small

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#971]

**Comment by ToninoTarsi** [comment]
Yes. To small in my 530dpi phone and also on kobo hd (300dpi). May I suggest to also add  a black glider with inverted colors that will be useful on kobo.. and may be also on Android

**Comment by pventafridda** [comment]
yes right

**Comment by pventafridda** [comment]
Resizing with RescalePixel or NIBL is not a good idea when dealing with very small values with no tolerances such as -5 9 0 -5 .. a value of 13 or 14 make a big difference in aspect then.
Easy and good result using different shapes and choosing by default the best one .

**Comment by pventafridda** [comment]
Better to check with latest commit if shapes are resized a bit bigger than before.
I am afraid that for some shapes such as the triangle they were originally made too small, and we should enlarge the vectors.

**Comment by pventafridda** [comment]
OK best solution is to have also bigger shapes, and let users choose.

**Comment by pventafridda** [comment]
On DITHER devices glider is inverted. By now it seems ok.
