### ISSUE TITLE
Android: Grid out of place in MM1 (Glitch)

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#977]
In Android version when switching to MM1 (or resizing the multimap) the grid is out of place but goes back to where is suppose to be.

![screenshot_20170127-092535](https://cloud.githubusercontent.com/assets/608650/22367889/6a00ad98-e473-11e6-97eb-003eaab3dbce.png)
![screenshot_20170127-092553](https://cloud.githubusercontent.com/assets/608650/22367890/6a035ca0-e473-11e6-9dd2-b53af5924571.png)

**Comment by parapenT1sta** [comment]
I tested with the latest beta version available and still the same :(

**Comment by pventafridda** [comment]
not for me, it is fixed

**Comment by parapenT1sta** [comment]
https://goo.gl/photos/oueuhJ6ofRkAPnTe9

Google Nexus 6P

**Comment by pventafridda** [comment]
It happens when reducing the top window opening the sideview.
It is only a glitch, due to different timing in drawing and updating some variable (1s latency).
Existing since v4 or v5, not worth to spend time on this issue really with all the things to do yet.

**Comment by parapenT1sta** [comment]
I also checked that it happens running LK8000 in Nimbus

**Comment by pventafridda** [comment]
it happens since 2014. since ever we made multimaps and on all platforms. 
it is the most unimportant problem we have .


In data 27 Febbraio 2017 7:46:11 PM Sérgio Da Silva 
<notifications@github.com> ha scritto:
