### ISSUE TITLE
DrawTaskPicto not painting correctly

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#982]
DrawTaskPicto is still using DrawScale and will not rescale properly.
Need same work as for DrawRunway.
Currently it gives a terrible result.

**Comment by brunotl** [comment]
Alredy fixed 
![image](https://cloud.githubusercontent.com/assets/858626/22472074/d15ab3bc-e7d4-11e6-9bf3-d18efb1509e6.png)

**Comment by brunotl** [comment]
Picto are draw in Contents rect, and are does not depends to ScreenScale

fixed by commit d08657a26fabe8545ee63d0496b3133ca0106cdc
