### ISSUE TITLE
Check demo waypoints and out - of - demo behaviour 

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#984]
After loading a new map, in sim mode users are stuck to home waypoint which in demo mode is in italy.
This is very wrong.

**Comment by brunotl** [comment]
when you load new maps, you also change waypoints file...
no real problem, it's like that from all time...

it's better to leave that as is, no need to add useless complicated code for manage this special case...

**Comment by pventafridda** [comment]
maybe removing the status of home from demo.cup is not a bad idea... no?



In data 31 Gennaio 2017 16:50:21 Bruno de Lacheisserie 
<notifications@github.com> ha scritto:

**Comment by brunotl** [comment]
agree

**Comment by pventafridda** [comment]
fixed in 6.1c by removing home from demo.cup and enlarging the demo area so that the center is positioned where we wanted
