### ISSUE TITLE
Multimaps ID - Help

### ISSUE THREAD

**Issue by parapenT1sta** [LK8000/LK8000#996]
There is no info inside of LK8000 about what each multimap is for. Usually who download Android apps don«t download or read manuals.

I think we should add a help button with the description for MM 1, 2, 3 and 4.

**Comment by pventafridda** [comment]
An help button wouldnt help much, we need an assistant and a tour of operations. But that's something requiring big efforts. Not only for developing, but also for concepting and writing and translating all the stuff. Not realistic to even think about it.
