### ISSUE TITLE
MUTEX working?

### ISSUE THREAD

**Issue by pventafridda** [LK8000/LK8000#999]
Is mutex protection against multiple instances working? Intestbench mode it should be write only, ignoring other mutex but nevertheless creating one. It doesnt seem to be working testing against a 6.0 that has full mutex protection.

**Comment by brunotl** [comment]
disabled PC with TESTBENCH enabled
https://github.com/LK8000/LK8000/commit/7fa18f7836a3aa761b43b9ab54209b910f87b191

  // use mutex to avoid multiple instances of lk8000 be running
#if (!((WINDOWSPC>0) && TESTBENCH)) && !defined(ANDROID)
   if (!Mutex.tryLock()) {
	  return(-2);
  }
#endif
